from django.urls import path
from . import api_views, printed_parts, camera_views

urlpatterns = [
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/cameras/", camera_views.camera_sources),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/cameras/discover/", camera_views.camera_discover),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/cameras/<str:camera_id>/", camera_views.camera_source_detail),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/cameras/<str:camera_id>/remove/", camera_views.camera_source_remove),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/cameras/<str:camera_id>/media/", camera_views.camera_media),
    path("printing/parts/", printed_parts.printed_parts, name="api-printed-parts"),
    path("printing/parts/<uuid:part_id>/", printed_parts.printed_part_detail, name="api-printed-part-detail"),
    path("dashboard/", api_views.dashboard, name="api-dashboard"),
    path("storage/", api_views.user_storage, name="api-user-storage"),
    path("search/", api_views.universal_search, name="api-universal-search"),
    path("tags/", api_views.maker_tags, name="api-maker-tags"),
    path("tags/resolve/", api_views.maker_tag_resolve_code, name="api-maker-tag-resolve-code"),
    path("tags/resolve/<uuid:public_token>/", api_views.maker_tag_resolve_token, name="api-maker-tag-resolve-token"),
    path("tags/<uuid:tag_id>/", api_views.maker_tag_detail, name="api-maker-tag-detail"),
    path("inventory/", api_views.inventory, name="api-inventory"),
    path("printing/", api_views.printing_overview, name="api-printing-overview"),
    path("printing/filaments/", api_views.printing_filaments, name="api-printing-filaments"),
    path("printing/filaments/<uuid:filament_id>/", api_views.printing_filament_detail, name="api-printing-filament-detail"),
    path("printing/catalogue/filaments/meta/", api_views.printing_filament_catalogue_meta, name="api-printing-filament-catalogue-meta"),
    path("printing/catalogue/filaments/", api_views.printing_filament_catalogue, name="api-printing-filament-catalogue"),
    path("printing/catalogue/filaments/import/", api_views.printing_filament_catalogue_import, name="api-printing-filament-catalogue-import"),
    path("printing/locations/", api_views.printing_locations, name="api-printing-locations"),
    path("printing/locations/<uuid:location_id>/", api_views.printing_location_detail, name="api-printing-location-detail"),
    path("printing/printers/", api_views.printing_printers, name="api-printing-printers"),
    path("printing/printers/<uuid:printer_id>/", api_views.printing_printer_detail, name="api-printing-printer-detail"),
    path("printing/printers/<uuid:printer_id>/connections/", api_views.printing_printer_connections, name="api-printing-printer-connections"),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/", api_views.printing_printer_connection_detail, name="api-printing-printer-connection-detail"),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/refresh/", api_views.printing_printer_connection_refresh, name="api-printing-printer-connection-refresh"),
    path("printing/printers/<uuid:printer_id>/connections/<uuid:connection_id>/control/", api_views.printing_printer_connection_control, name="api-printing-printer-connection-control"),
    path("printing/spools/", api_views.printing_spools, name="api-printing-spools"),
    path("printing/spools/<uuid:spool_id>/", api_views.printing_spool_detail, name="api-printing-spool-detail"),
    path("printing/slots/<uuid:slot_id>/add-to-inventory/", api_views.printing_slot_add_to_inventory, name="api-printing-slot-add-to-inventory"),
    path("printing/models/", api_views.printing_models, name="api-printing-models"),
    path("printing/models/<uuid:model_id>/", api_views.printing_model_detail, name="api-printing-model-detail"),
    path("printing/models/<uuid:model_id>/revisions/", api_views.printing_model_revisions, name="api-printing-model-revisions"),
    path("printing/models/<uuid:model_id>/revisions/upload/", api_views.printing_model_revision_upload, name="api-printing-model-revision-upload"),
    path("printing/models/<uuid:model_id>/revisions/<uuid:revision_id>/", api_views.printing_model_revision_detail, name="api-printing-model-revision-detail"),
    path("printing/models/<uuid:model_id>/revisions/<uuid:revision_id>/analyse/", api_views.printing_revision_analyse, name="api-printing-revision-analyse"),
    path("printing/models/<uuid:model_id>/revisions/<uuid:revision_id>/assets/", api_views.printing_revision_assets, name="api-printing-revision-assets"),
    path("printing/models/<uuid:model_id>/revisions/<uuid:revision_id>/assets/<uuid:link_id>/", api_views.printing_revision_asset_detail, name="api-printing-revision-asset-detail"),
    path("printing/jobs/", api_views.printing_jobs, name="api-printing-jobs"),
    path("printing/jobs/<uuid:job_id>/", api_views.printing_job_detail, name="api-printing-job-detail"),
    path("inventory/<uuid:item_id>/", api_views.inventory_detail, name="api-inventory-detail"),
    path("boards/", api_views.boards, name="api-boards"),
    path("boards/<uuid:board_id>/", api_views.board_detail, name="api-board-detail"),
    path("boards/<uuid:board_id>/enrich/", api_views.board_enrich, name="api-board-enrich"),
    path("boards/<uuid:board_id>/image/", api_views.board_image, name="api-board-image"),
    path("components/", api_views.components, name="api-components"),
    path("components/<uuid:component_id>/", api_views.component_detail, name="api-component-detail"),
    path("components/<uuid:component_id>/image/", api_views.component_image, name="api-component-image"),
    path("files/", api_views.files_lookup, name="api-files"),
    path("files/<uuid:asset_id>/", api_views.file_detail, name="api-file-detail"),
    path("files/<uuid:asset_id>/versions/", api_views.file_versions, name="api-file-versions"),
    path("projects/", api_views.projects_lookup, name="api-projects"),
    path("projects/<uuid:project_id>/", api_views.project_detail, name="api-project-detail"),
    path("projects/<uuid:project_id>/cover/", api_views.project_cover, name="api-project-cover"),
    path("projects/<uuid:project_id>/gallery/", api_views.project_gallery, name="api-project-gallery"),
    path("projects/<uuid:project_id>/gallery/<uuid:asset_id>/", api_views.project_gallery_delete, name="api-project-gallery-delete"),
    path("projects/<uuid:project_id>/files/", api_views.project_files, name="api-project-files"),
    path("projects/<uuid:project_id>/files/<uuid:asset_id>/", api_views.project_file_detail, name="api-project-file-detail"),
    path("wiring/", api_views.wiring_lab_diagrams, name="api-wiring-lab"),
    path("wiring/<uuid:diagram_id>/", api_views.wiring_lab_diagram_detail, name="api-wiring-lab-detail"),
    path("wiring/<uuid:diagram_id>/assign-project/", api_views.wiring_lab_assign_project, name="api-wiring-lab-assign-project"),
    path("projects/<uuid:project_id>/wiring/", api_views.project_wiring_diagrams, name="api-project-wiring-diagrams"),
    path("projects/<uuid:project_id>/wiring/<uuid:diagram_id>/", api_views.project_wiring_diagram_detail, name="api-project-wiring-diagram-detail"),
    path("projects/<uuid:project_id>/repositories/", api_views.project_repositories, name="api-project-repositories"),
    path("projects/<uuid:project_id>/repositories/<int:repository_id>/", api_views.project_repository_detail, name="api-project-repository-detail"),
    path("projects/<uuid:project_id>/bom/", api_views.project_bom_items, name="api-project-bom-items"),
    path("projects/<uuid:project_id>/bom/<int:bom_id>/", api_views.project_bom_item_detail, name="api-project-bom-item-detail"),
    path("projects/<uuid:project_id>/bom/<int:bom_id>/allocations/", api_views.project_bom_allocations, name="api-project-bom-allocations"),
    path("projects/<uuid:project_id>/bom/<int:bom_id>/allocations/<int:allocation_id>/", api_views.project_bom_allocation_detail, name="api-project-bom-allocation-detail"),
    path("import/board/preview/", api_views.import_board_preview, name="api-import-board-preview"),
    path("import/board/commit/", api_views.import_board_commit, name="api-import-board-commit"),
    path("config/", api_views.public_config, name="api-config"),
    path("attributions/", api_views.attributions, name="api-attributions"),
    path("settings/printing-integrations/", api_views.printing_integration_settings, name="api-printing-integration-settings"),
    path("settings/printing-integrations/<str:provider>/", api_views.printing_integration_detail, name="api-printing-integration-detail"),
    path("settings/printing-integrations/<str:provider>/test/", api_views.printing_integration_test, name="api-printing-integration-test"),
    path("settings/printing-integrations/<str:provider>/sync/", api_views.printing_integration_sync_now, name="api-printing-integration-sync-now"),
    path("settings/printing-integrations/<str:provider>/reviews/", api_views.printing_integration_reviews, name="api-printing-integration-reviews"),
    path("settings/printing-integrations/<str:provider>/reviews/<str:external_id>/", api_views.printing_integration_review_resolve, name="api-printing-integration-review-resolve"),
    path("settings/catalogue-maintenance/", api_views.catalogue_maintenance_settings, name="api-catalogue-maintenance-settings"),
    path("settings/catalogue-coverage/", api_views.catalogue_coverage, name="api-catalogue-coverage"),
    path("settings/catalogue-maintenance/run/", api_views.catalogue_maintenance_run_now, name="api-catalogue-maintenance-run"),
    path("settings/backups/", api_views.admin_backups, name="api-admin-backups"),
    path("settings/backups/create/", api_views.admin_backup_create, name="api-admin-backup-create"),
    path("settings/backups/<str:backup_id>/validate/", api_views.admin_backup_validate, name="api-admin-backup-validate"),
    path("settings/backups/<str:backup_id>/download/", api_views.admin_backup_download, name="api-admin-backup-download"),
    path("settings/backups/<str:backup_id>/", api_views.admin_backup_delete, name="api-admin-backup-delete"),
    path("settings/storage-policy/", api_views.admin_storage_policy, name="api-admin-storage-policy"),
    path("settings/users/", api_views.admin_users, name="api-admin-users"),
    path("settings/users/<int:user_id>/", api_views.admin_user_detail, name="api-admin-user-detail"),
    path("settings/users/<int:user_id>/purge/", api_views.admin_user_purge, name="api-admin-user-purge"),
    path("settings/users/<int:user_id>/delete/", api_views.admin_user_delete, name="api-admin-user-delete"),
]


