from django.urls import path
from . import api_views

urlpatterns = [
    path("dashboard/", api_views.dashboard, name="api-dashboard"),
    path("inventory/", api_views.inventory, name="api-inventory"),
    path("inventory/<uuid:item_id>/", api_views.inventory_detail, name="api-inventory-detail"),
    path("boards/", api_views.boards, name="api-boards"),
    path("boards/<uuid:board_id>/", api_views.board_detail, name="api-board-detail"),
    path("boards/<uuid:board_id>/enrich/", api_views.board_enrich, name="api-board-enrich"),
    path("boards/<uuid:board_id>/image/", api_views.board_image, name="api-board-image"),
    path("components/", api_views.components, name="api-components"),
    path("components/<uuid:component_id>/", api_views.component_detail, name="api-component-detail"),
    path("components/<uuid:component_id>/image/", api_views.component_image, name="api-component-image"),
    path("files/", api_views.files_lookup, name="api-files"),
    path("files/<uuid:asset_id>/", api_views.file_detail, name="api-file-detail"),
    path("projects/", api_views.projects_lookup, name="api-projects"),
    path("projects/<uuid:project_id>/", api_views.project_detail, name="api-project-detail"),
    path("projects/<uuid:project_id>/cover/", api_views.project_cover, name="api-project-cover"),
    path("projects/<uuid:project_id>/gallery/", api_views.project_gallery, name="api-project-gallery"),
    path("projects/<uuid:project_id>/gallery/<uuid:asset_id>/", api_views.project_gallery_delete, name="api-project-gallery-delete"),
    path("projects/<uuid:project_id>/files/", api_views.project_files, name="api-project-files"),
    path("projects/<uuid:project_id>/files/<uuid:asset_id>/", api_views.project_file_detail, name="api-project-file-detail"),
    path("projects/<uuid:project_id>/repositories/", api_views.project_repositories, name="api-project-repositories"),
    path("projects/<uuid:project_id>/repositories/<int:repository_id>/", api_views.project_repository_detail, name="api-project-repository-detail"),
    path("import/board/preview/", api_views.import_board_preview, name="api-import-board-preview"),
    path("import/board/commit/", api_views.import_board_commit, name="api-import-board-commit"),
    path("config/", api_views.public_config, name="api-config"),
    path("attributions/", api_views.attributions, name="api-attributions"),
    path("settings/catalogue-maintenance/", api_views.catalogue_maintenance_settings, name="api-catalogue-maintenance-settings"),
    path("settings/catalogue-maintenance/run/", api_views.catalogue_maintenance_run_now, name="api-catalogue-maintenance-run"),
]
