"""Curated MakerVault starter catalogue data.

This is intentionally source-agnostic starter metadata, not a claim that every
variant from every manufacturer is represented. Imported/manufacturer data can
later enrich these records without changing the physical inventory model.
"""

def board(manufacturer, name, family="", mcu="", architecture="", compat=None, **kwargs):
    return {
        "manufacturer": manufacturer,
        "name": name,
        "family": family,
        "mcu": mcu,
        "architecture": architecture,
        "compat": compat or [],
        **kwargs,
    }


BOARD_DEFINITIONS = [
    board("Espressif","ESP32-DevKitC","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],flash_mb=4,ram_kb=520,wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-S2-DevKitC-1","ESP32-S2","ESP32-S2","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-S3-DevKitC-1","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-C3-DevKitM-1","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-C6-DevKitC-1","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Espressif","ESP32-H2-DevKitM-1","ESP32-H2","ESP32-H2","RISC-V",["Arduino","PlatformIO","ESPHome"],bluetooth=True,zigbee=True,thread=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-P4-Function-EV-Board","ESP32-P4","ESP32-P4","RISC-V",["ESP-IDF"],usb_connector="USB-C"),
    board("Generic","ESP8266 NodeMCU","ESP8266","ESP8266","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,usb_connector="Micro-USB"),
    board("Generic","Wemos D1 Mini (ESP8266)","ESP8266","ESP8266","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,usb_connector="Micro-USB"),
    board("Generic","ESP32-CAM AI-Thinker style","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Generic","ESP32 C3 Super Mini","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],flash_mb=4,ram_kb=400,gpio_count=13,wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Generic","ESP32-S3 Super Mini","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Generic","ESP32-C6 Super Mini","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Generic","ESP32-H2 Super Mini","ESP32-H2","ESP32-H2","RISC-V",["Arduino","PlatformIO","ESPHome"],bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Raspberry Pi","Raspberry Pi Zero","Raspberry Pi Zero","BCM2835"),
    board("Raspberry Pi","Raspberry Pi Zero W","Raspberry Pi Zero","BCM2835",wifi=True,bluetooth=True),
    board("Raspberry Pi","Raspberry Pi Zero 2 W","Raspberry Pi Zero","BCM2710A1",wifi=True,bluetooth=True),
    board("Raspberry Pi","Raspberry Pi 3 Model B+","Raspberry Pi","BCM2837B0",wifi=True,bluetooth=True),
    board("Raspberry Pi","Raspberry Pi 4 Model B","Raspberry Pi","BCM2711",wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Raspberry Pi","Raspberry Pi 5","Raspberry Pi","BCM2712",wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Raspberry Pi","Raspberry Pi Pico","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Raspberry Pi","Raspberry Pi Pico W","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Raspberry Pi","Raspberry Pi Pico 2","RP2350","RP2350","ARM Cortex-M33 / RISC-V",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Raspberry Pi","Raspberry Pi Pico 2 W","RP2350","RP2350","ARM Cortex-M33 / RISC-V",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Arduino","Uno R3","AVR","ATmega328P","AVR",["Arduino","PlatformIO"],usb_connector="USB-B"),
    board("Arduino","Uno R4 Minima","Renesas RA4M1","RA4M1","ARM Cortex-M4",["Arduino"],usb_connector="USB-C"),
    board("Arduino","Uno R4 WiFi","Renesas RA4M1","RA4M1 + ESP32-S3","ARM Cortex-M4",["Arduino"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Arduino","Nano","AVR","ATmega328P","AVR",["Arduino","PlatformIO"],usb_connector="Mini-USB"),
    board("Arduino","Nano Every","AVR","ATmega4809","AVR",["Arduino"],usb_connector="Micro-USB"),
    board("Arduino","Nano 33 IoT","SAMD21","SAMD21","ARM Cortex-M0+",["Arduino"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Arduino","Nano RP2040 Connect","RP2040","RP2040","ARM Cortex-M0+",["Arduino"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Arduino","Nano ESP32","ESP32-S3","ESP32-S3","Xtensa",["Arduino","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Arduino","Mega 2560 Rev3","AVR","ATmega2560","AVR",["Arduino","PlatformIO"],usb_connector="USB-B"),
    board("Arduino","Leonardo","AVR","ATmega32U4","AVR",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Arduino","Micro","AVR","ATmega32U4","AVR",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Seeed Studio","XIAO ESP32C3","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Seeed Studio","XIAO ESP32C6","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Seeed Studio","XIAO ESP32S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Seeed Studio","XIAO RP2040","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("Seeed Studio","XIAO RP2350","RP2350","RP2350","ARM Cortex-M33 / RISC-V",["Arduino"],usb_connector="USB-C"),
    board("M5Stack","Atom Lite","ESP32","ESP32-PICO-D4","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","Atom S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","Core2","ESP32","ESP32-D0WDQ6-V3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","CoreS3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","Stamp C3","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Adafruit","Feather ESP32-S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Adafruit","QT Py ESP32-C3","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Adafruit","Feather RP2040","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("SparkFun","Pro Micro RP2040","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("PJRC","Teensy 4.0","Teensy","i.MX RT1062","ARM Cortex-M7",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("PJRC","Teensy 4.1","Teensy","i.MX RT1062","ARM Cortex-M7",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Waveshare","ESP32-S3-Zero","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Waveshare","ESP32-C6-Zero","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Waveshare","RP2040-Zero","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("Waveshare","RP2040-Plus","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("LilyGo","T-Display","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T-Display-S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T-Deck","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T-Beam","ESP32","ESP32","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T3-S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Heltec","WiFi LoRa 32 V3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Heltec","Wireless Stick Lite V3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Olimex","ESP32-POE","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Olimex","ESP32-POE-ISO","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Olimex","ESP32-EVB","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Elecrow","CrowPanel ESP32 2.8in HMI","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Elecrow","CrowPanel ESP32 3.5in HMI","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Generic","ESP32-2432S028R CYD","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("DFRobot","FireBeetle 2 ESP32-E","ESP32","ESP32-WROOM-32E","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
]


CATEGORY_TREE = {
    "Passives": None,
    "Semiconductors": None,
    "LEDs & Lighting": None,
    "Displays": None,
    "Sensors": None,
    "Communications": None,
    "Audio": None,
    "Controls": None,
    "Power": None,
    "Relays & Switching": None,
    "Prototyping": None,
    "Connectors": None,
    "Storage": None,
    "Timing": None,
    "Motors & Drivers": None,
    "Cameras & Vision": None,
    "Logic & Level Shifting": None,
    "Mechanical & Thermal": None,
    "Test & Measurement": None,
}


def component(category, name, part_number="", manufacturer="Generic", description="", **specifications):
    return {
        "category": category,
        "manufacturer": manufacturer,
        "name": name,
        "part_number": part_number,
        "description": description,
        "specifications": specifications,
    }


COMPONENT_DEFINITIONS = [
    component("Passives","Resistor assortment 1/4W",type="resistor",power="0.25 W",package="through-hole"),
    component("Passives","220 ohm resistor","",type="resistor",value="220 Ω",power="0.25 W",package="through-hole"),
    component("Passives","1k ohm resistor","",type="resistor",value="1 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","4.7k ohm resistor","",type="resistor",value="4.7 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","10k ohm resistor","",type="resistor",value="10 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","100k ohm resistor","",type="resistor",value="100 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","Ceramic capacitor assortment","",type="capacitor",package="through-hole"),
    component("Passives","100nF ceramic capacitor","",type="capacitor",value="100 nF",package="through-hole"),
    component("Passives","10uF electrolytic capacitor","",type="capacitor",value="10 µF",package="radial"),
    component("Passives","100uF electrolytic capacitor","",type="capacitor",value="100 µF",package="radial"),
    component("Passives","470uF electrolytic capacitor","",type="capacitor",value="470 µF",package="radial"),

    component("Semiconductors","1N4148 signal diode","1N4148",type="diode",package="DO-35"),
    component("Semiconductors","1N4007 rectifier diode","1N4007",type="diode",package="DO-41"),
    component("Semiconductors","SS34 Schottky diode","SS34",type="diode",package="SMA"),
    component("Semiconductors","2N2222 NPN transistor","2N2222",type="transistor",package="TO-92"),
    component("Semiconductors","BC547 NPN transistor","BC547",type="transistor",package="TO-92"),
    component("Semiconductors","2N3904 NPN transistor","2N3904",type="transistor",package="TO-92"),
    component("Semiconductors","IRLZ44N logic-level N-MOSFET","IRLZ44N",type="mosfet",package="TO-220"),
    component("Semiconductors","AO3400A N-MOSFET","AO3400A",type="mosfet",package="SOT-23"),
    component("Semiconductors","PC817 optocoupler","PC817",type="optocoupler",package="DIP-4"),
    component("Semiconductors","AMS1117-3.3 regulator","AMS1117-3.3",type="regulator",output="3.3 V",package="SOT-223"),
    component("Semiconductors","L7805 5V regulator","L7805",type="regulator",output="5 V",package="TO-220"),

    component("LEDs & Lighting","5mm red LED","",type="led",colour="red",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm green LED","",type="led",colour="green",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm blue LED","",type="led",colour="blue",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm white LED","",type="led",colour="white",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm RGB LED common cathode","",type="rgb-led",package="5 mm through-hole"),
    component("LEDs & Lighting","WS2812B addressable RGB LED","WS2812B",type="addressable-led",protocol="single-wire",voltage="5 V"),
    component("LEDs & Lighting","SK6812 RGBW addressable LED","SK6812",type="addressable-led",protocol="single-wire",voltage="5 V"),
    component("LEDs & Lighting","WS2812 8 LED ring","",type="led-ring",protocol="single-wire",led_count=8,voltage="5 V"),
    component("LEDs & Lighting","WS2812 12 LED ring","",type="led-ring",protocol="single-wire",led_count=12,voltage="5 V"),
    component("LEDs & Lighting","WS2812 16 LED ring","",type="led-ring",protocol="single-wire",led_count=16,voltage="5 V"),
    component("LEDs & Lighting","WS2812 24 LED ring","",type="led-ring",protocol="single-wire",led_count=24,voltage="5 V"),
    component("LEDs & Lighting","WS2812 8x8 RGB matrix","",type="led-matrix",protocol="single-wire",resolution="8x8",voltage="5 V"),
    component("LEDs & Lighting","WS2812B LED strip","",type="led-strip",protocol="single-wire",voltage="5 V"),

    component("Displays","SSD1306 0.96in OLED 128x64 I2C","SSD1306",type="oled",interface="I2C",resolution="128x64",voltage="3.3-5 V"),
    component("Displays","SH1106 1.3in OLED 128x64 I2C","SH1106",type="oled",interface="I2C",resolution="128x64"),
    component("Displays","SSD1327 1.5in OLED 128x128","SSD1327",type="oled",interface="I2C/SPI",resolution="128x128"),
    component("Displays","ST7735 1.8in TFT 160x128","ST7735",type="tft",interface="SPI",resolution="160x128"),
    component("Displays","ST7789 1.9in TFT 170x320","ST7789",type="tft",interface="SPI",resolution="170x320"),
    component("Displays","ILI9341 2.4in TFT 320x240","ILI9341",type="tft",interface="SPI",resolution="320x240"),
    component("Displays","ILI9488 3.5in TFT 480x320","ILI9488",type="tft",interface="SPI",resolution="480x320"),
    component("Displays","GC9A01 1.28in round TFT 240x240","GC9A01",type="round-tft",interface="SPI",resolution="240x240"),
    component("Displays","LCD1602 character display","HD44780",type="character-lcd",interface="parallel",resolution="16x2"),
    component("Displays","LCD2004 character display","HD44780",type="character-lcd",interface="parallel",resolution="20x4"),
    component("Displays","PCF8574 I2C LCD backpack","PCF8574",type="display-adapter",interface="I2C"),
    component("Displays","TM1637 4-digit 7-segment display","TM1637",type="7-segment",interface="2-wire"),
    component("Displays","MAX7219 8x8 LED matrix module","MAX7219",type="led-matrix",interface="SPI-like",resolution="8x8"),
    component("Displays","2.13in e-paper display module","",type="e-paper",interface="SPI"),

    component("Sensors","BME280 temperature/humidity/pressure sensor","BME280",manufacturer="Bosch",type="environment",interface="I2C/SPI",measures=["temperature","humidity","pressure"]),
    component("Sensors","BMP280 pressure/temperature sensor","BMP280",manufacturer="Bosch",type="environment",interface="I2C/SPI",measures=["temperature","pressure"]),
    component("Sensors","BMP388 precision pressure sensor","BMP388",manufacturer="Bosch",type="environment",interface="I2C/SPI",measures=["temperature","pressure"]),
    component("Sensors","SHT31 temperature/humidity sensor","SHT31",manufacturer="Sensirion",type="environment",interface="I2C",measures=["temperature","humidity"]),
    component("Sensors","SHT40 temperature/humidity sensor","SHT40",manufacturer="Sensirion",type="environment",interface="I2C",measures=["temperature","humidity"]),
    component("Sensors","AHT20 temperature/humidity sensor","AHT20",manufacturer="ASAIR",type="environment",interface="I2C",measures=["temperature","humidity"]),
    component("Sensors","DHT22 temperature/humidity sensor","DHT22",manufacturer="Aosong",type="environment",interface="single-wire",measures=["temperature","humidity"]),
    component("Sensors","DS18B20 waterproof temperature probe","DS18B20",manufacturer="Maxim / Analog Devices",type="temperature",interface="1-Wire"),
    component("Sensors","BH1750 light sensor","BH1750",manufacturer="ROHM",type="light",interface="I2C"),
    component("Sensors","TSL2561 digital light sensor","TSL2561",manufacturer="ams",type="light",interface="I2C"),
    component("Sensors","MPU6050 6-axis IMU","MPU6050",manufacturer="TDK InvenSense",type="imu",interface="I2C",axes=6),
    component("Sensors","MPU9250 9-axis IMU","MPU9250",manufacturer="TDK InvenSense",type="imu",interface="I2C/SPI",axes=9),
    component("Sensors","ADXL345 3-axis accelerometer","ADXL345",manufacturer="Analog Devices",type="accelerometer",interface="I2C/SPI",axes=3),
    component("Sensors","VL53L0X time-of-flight distance sensor","VL53L0X",manufacturer="STMicroelectronics",type="distance",interface="I2C"),
    component("Sensors","VL53L1X time-of-flight distance sensor","VL53L1X",manufacturer="STMicroelectronics",type="distance",interface="I2C"),
    component("Sensors","HC-SR04 ultrasonic distance sensor","HC-SR04",type="distance",interface="trigger/echo",voltage="5 V"),
    component("Sensors","HC-SR501 PIR motion sensor","HC-SR501",type="motion",interface="digital"),
    component("Sensors","RCWL-0516 microwave motion sensor","RCWL-0516",type="motion",interface="digital"),
    component("Sensors","LD2410B mmWave presence sensor","LD2410B",manufacturer="Hi-Link",type="presence",interface="UART/Bluetooth"),
    component("Sensors","LD2410C mmWave presence sensor","LD2410C",manufacturer="Hi-Link",type="presence",interface="UART/Bluetooth"),
    component("Sensors","A3144 Hall effect sensor","A3144",type="magnetic",interface="digital"),
    component("Sensors","Magnetic reed switch","",type="magnetic",interface="digital"),
    component("Sensors","Capacitive soil moisture sensor v1.2","",type="soil-moisture",interface="analog"),
    component("Sensors","HX711 load-cell amplifier","HX711",type="weight",interface="2-wire"),
    component("Sensors","1kg load cell","",type="load-cell",capacity="1 kg"),
    component("Sensors","5kg load cell","",type="load-cell",capacity="5 kg"),
    component("Sensors","MQ-2 gas/smoke sensor module","MQ-2",type="gas",interface="analog/digital"),
    component("Sensors","MQ-135 air-quality sensor module","MQ-135",type="gas",interface="analog/digital"),
    component("Sensors","INA219 current/voltage monitor","INA219",manufacturer="Texas Instruments",type="power-monitor",interface="I2C"),
    component("Sensors","INA226 current/voltage monitor","INA226",manufacturer="Texas Instruments",type="power-monitor",interface="I2C"),
    component("Sensors","ACS712 current sensor module","ACS712",manufacturer="Allegro",type="current",interface="analog"),
    component("Sensors","ADS1115 16-bit ADC module","ADS1115",manufacturer="Texas Instruments",type="adc",interface="I2C",resolution="16-bit"),

    component("Communications","HC-05 Bluetooth serial module","HC-05",type="bluetooth",interface="UART"),
    component("Communications","HC-06 Bluetooth serial module","HC-06",type="bluetooth",interface="UART"),
    component("Communications","nRF24L01+ 2.4GHz radio module","nRF24L01+",manufacturer="Nordic Semiconductor",type="2.4ghz-radio",interface="SPI"),
    component("Communications","nRF24L01+ PA/LNA radio module","nRF24L01+",manufacturer="Nordic Semiconductor",type="2.4ghz-radio",interface="SPI"),
    component("Communications","SX1278 LoRa module","SX1278",manufacturer="Semtech",type="lora",interface="SPI"),
    component("Communications","RFM95W LoRa radio module","RFM95W",manufacturer="HopeRF",type="lora",interface="SPI"),
    component("Communications","W5500 Ethernet module","W5500",manufacturer="WIZnet",type="ethernet",interface="SPI"),
    component("Communications","ENC28J60 Ethernet module","ENC28J60",manufacturer="Microchip",type="ethernet",interface="SPI"),
    component("Communications","MCP2515 CAN bus module","MCP2515",manufacturer="Microchip",type="can",interface="SPI"),
    component("Communications","SN65HVD230 CAN transceiver module","SN65HVD230",manufacturer="Texas Instruments",type="can-transceiver",interface="CAN"),
    component("Communications","MAX485 RS-485 transceiver module","MAX485",manufacturer="Maxim / Analog Devices",type="rs485",interface="UART"),
    component("Communications","RC522 RFID reader module","MFRC522",manufacturer="NXP",type="rfid",interface="SPI"),
    component("Communications","PN532 NFC/RFID module","PN532",manufacturer="NXP",type="nfc",interface="I2C/SPI/UART"),
    component("Communications","CP2102 USB-to-UART module","CP2102",manufacturer="Silicon Labs",type="usb-serial",interface="USB/UART"),
    component("Communications","CH340G USB-to-UART module","CH340G",manufacturer="WCH",type="usb-serial",interface="USB/UART"),

    component("Audio","INMP441 I2S MEMS microphone module","INMP441",type="microphone",interface="I2S"),
    component("Audio","SPH0645 I2S MEMS microphone module","SPH0645",manufacturer="Knowles",type="microphone",interface="I2S"),
    component("Audio","MAX98357A I2S amplifier module","MAX98357A",manufacturer="Maxim / Analog Devices",type="amplifier",interface="I2S"),
    component("Audio","NS4168 I2S amplifier module","NS4168",type="amplifier",interface="I2S"),
    component("Audio","PAM8403 stereo amplifier module","PAM8403",type="amplifier",interface="analog",power="2x3 W"),
    component("Audio","DFPlayer Mini MP3 module","DFPlayer Mini",type="audio-player",interface="UART"),
    component("Audio","Active piezo buzzer module","",type="buzzer",interface="digital"),
    component("Audio","Passive piezo buzzer","",type="buzzer",interface="PWM"),
    component("Audio","8 ohm 3W speaker","",type="speaker",impedance="8 Ω",power="3 W"),

    component("Controls","EC11 rotary encoder","EC11",type="rotary-encoder",interface="quadrature"),
    component("Controls","Momentary tactile push button","",type="button",interface="digital"),
    component("Controls","Illuminated momentary push button","",type="button",interface="digital"),
    component("Controls","SPST toggle switch","",type="switch"),
    component("Controls","Rocker switch","",type="switch"),
    component("Controls","10k potentiometer","",type="potentiometer",value="10 kΩ",interface="analog"),
    component("Controls","10k slide potentiometer","",type="potentiometer",value="10 kΩ",interface="analog"),
    component("Controls","PS2-style joystick module","",type="joystick",interface="analog/digital"),
    component("Controls","4x4 matrix keypad","",type="keypad",interface="matrix",keys=16),
    component("Controls","TTP223 capacitive touch module","TTP223",type="touch",interface="digital"),

    component("Power","LM2596 adjustable buck converter module","LM2596",type="buck",input="4-40 V",output="1.25-35 V"),
    component("Power","MP1584 mini adjustable buck converter","MP1584",type="buck",input="4.5-28 V"),
    component("Power","MT3608 boost converter module","MT3608",type="boost",input="2-24 V"),
    component("Power","XL4015 adjustable buck converter module","XL4015",type="buck",input="5-36 V"),
    component("Power","TP4056 USB-C Li-ion charger module","TP4056",type="battery-charger",connector="USB-C",cells="1S"),
    component("Power","TP4056 Micro-USB Li-ion charger module","TP4056",type="battery-charger",connector="Micro-USB",cells="1S"),
    component("Power","1S Li-ion protection/BMS module","",type="bms",cells="1S"),
    component("Power","AMS1117 3.3V regulator module","AMS1117-3.3",type="linear-regulator",output="3.3 V"),
    component("Power","USB-C PD trigger module","",type="usb-pd",connector="USB-C"),
    component("Power","DC barrel jack breakout","",type="power-connector",connector="5.5x2.1 mm"),

    component("Relays & Switching","5V single-channel relay module","",type="relay",channels=1,coil_voltage="5 V"),
    component("Relays & Switching","5V dual-channel relay module","",type="relay",channels=2,coil_voltage="5 V"),
    component("Relays & Switching","5V four-channel relay module","",type="relay",channels=4,coil_voltage="5 V"),
    component("Relays & Switching","Logic-level MOSFET switch module","",type="mosfet-switch",interface="digital/PWM"),

    component("Logic & Level Shifting","BSS138 4-channel bidirectional level shifter","BSS138",type="level-shifter",channels=4),
    component("Logic & Level Shifting","TXS0108E 8-channel level shifter","TXS0108E",manufacturer="Texas Instruments",type="level-shifter",channels=8),
    component("Logic & Level Shifting","74HC595 shift register","74HC595",type="shift-register",interface="SPI-like",bits=8),
    component("Logic & Level Shifting","74HC165 parallel-in shift register","74HC165",type="shift-register",interface="SPI-like",bits=8),
    component("Logic & Level Shifting","MCP23017 16-bit GPIO expander","MCP23017",manufacturer="Microchip",type="gpio-expander",interface="I2C",gpio=16),
    component("Logic & Level Shifting","PCF8574 8-bit GPIO expander","PCF8574",type="gpio-expander",interface="I2C",gpio=8),

    component("Prototyping","830-point solderless breadboard","",type="breadboard",points=830),
    component("Prototyping","400-point solderless breadboard","",type="breadboard",points=400),
    component("Prototyping","170-point mini breadboard","",type="breadboard",points=170),
    component("Prototyping","2.54mm perfboard","",type="perfboard",pitch="2.54 mm"),
    component("Prototyping","Male header strip 2.54mm","",type="header",pitch="2.54 mm"),
    component("Prototyping","Female header strip 2.54mm","",type="header",pitch="2.54 mm"),
    component("Prototyping","Dupont jumper wire set M-M","",type="jumper-wire"),
    component("Prototyping","Dupont jumper wire set M-F","",type="jumper-wire"),
    component("Prototyping","Dupont jumper wire set F-F","",type="jumper-wire"),

    component("Connectors","Dupont crimp housing and pin kit","",type="connector",pitch="2.54 mm"),
    component("Connectors","JST-XH connector kit","JST-XH",type="connector",pitch="2.5 mm"),
    component("Connectors","JST-PH connector kit","JST-PH",type="connector",pitch="2.0 mm"),
    component("Connectors","JST-SH connector kit","JST-SH",type="connector",pitch="1.0 mm"),
    component("Connectors","2-pin screw terminal block","",type="terminal-block"),
    component("Connectors","3-pin screw terminal block","",type="terminal-block"),
    component("Connectors","XT30 connector pair","XT30",type="power-connector"),
    component("Connectors","XT60 connector pair","XT60",type="power-connector"),

    component("Storage","MicroSD SPI module","",type="flash-storage",interface="SPI"),
    component("Storage","Full-size SD card SPI module","",type="flash-storage",interface="SPI"),
    component("Storage","AT24C32 I2C EEPROM module","AT24C32",type="eeprom",interface="I2C",capacity="32 Kbit"),
    component("Storage","MB85RC256 I2C FRAM module","MB85RC256",manufacturer="Fujitsu",type="fram",interface="I2C",capacity="256 Kbit"),

    component("Timing","DS3231 RTC module","DS3231",manufacturer="Maxim / Analog Devices",type="rtc",interface="I2C"),
    component("Timing","DS1307 RTC module","DS1307",manufacturer="Maxim / Analog Devices",type="rtc",interface="I2C"),
    component("Timing","PCF8563 RTC module","PCF8563",manufacturer="NXP",type="rtc",interface="I2C"),

    component("Motors & Drivers","SG90 9g micro servo","SG90",type="servo",interface="PWM"),
    component("Motors & Drivers","MG996R high-torque servo","MG996R",type="servo",interface="PWM"),
    component("Motors & Drivers","28BYJ-48 stepper motor","28BYJ-48",type="stepper"),
    component("Motors & Drivers","ULN2003 stepper driver board","ULN2003",type="motor-driver"),
    component("Motors & Drivers","A4988 stepper motor driver module","A4988",manufacturer="Allegro",type="stepper-driver"),
    component("Motors & Drivers","DRV8825 stepper motor driver module","DRV8825",manufacturer="Texas Instruments",type="stepper-driver"),
    component("Motors & Drivers","TMC2209 stepper motor driver module","TMC2209",manufacturer="Trinamic",type="stepper-driver",interface="step/dir/UART"),
    component("Motors & Drivers","L298N dual H-bridge module","L298N",manufacturer="STMicroelectronics",type="dc-motor-driver"),
    component("Motors & Drivers","TB6612FNG dual motor driver","TB6612FNG",manufacturer="Toshiba",type="dc-motor-driver"),
    component("Motors & Drivers","BTS7960 high-current motor driver","BTS7960",type="dc-motor-driver"),
    component("Motors & Drivers","PCA9685 16-channel PWM/servo driver","PCA9685",manufacturer="NXP",type="pwm-driver",interface="I2C",channels=16),

    component("Cameras & Vision","OV2640 camera module","OV2640",type="camera",resolution="2 MP"),
    component("Cameras & Vision","OV5640 camera module","OV5640",type="camera",resolution="5 MP"),

    component("Mechanical & Thermal","5V 40mm cooling fan","",type="fan",size="40 mm",voltage="5 V"),
    component("Mechanical & Thermal","12V 40mm cooling fan","",type="fan",size="40 mm",voltage="12 V"),
    component("Mechanical & Thermal","M2 heat-set insert assortment","",type="heat-set-insert",thread="M2"),
    component("Mechanical & Thermal","M3 heat-set insert assortment","",type="heat-set-insert",thread="M3"),
    component("Mechanical & Thermal","M3 screw assortment","",type="fastener",thread="M3"),
    component("Mechanical & Thermal","Neodymium magnet assortment","",type="magnet"),

    component("Test & Measurement","USB inline voltage/current meter","",type="power-meter",interface="USB"),
    component("Test & Measurement","Mini logic analyser 8-channel","",type="logic-analyser",channels=8),
]
