"""Curated MakerVault starter catalogue data.

This is intentionally source-agnostic starter metadata, not a claim that every
variant from every manufacturer is represented. Imported/manufacturer data can
later enrich these records without changing the physical inventory model.
"""

def board(manufacturer, name, family="", mcu="", architecture="", compat=None, **kwargs):
    return {
        "manufacturer": manufacturer,
        "name": name,
        "family": family,
        "mcu": mcu,
        "architecture": architecture,
        "compat": compat or [],
        **kwargs,
    }


BOARD_DEFINITIONS = [
    board("Espressif","ESP32-DevKitC","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],flash_mb=4,ram_kb=520,wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-S2-DevKitC-1","ESP32-S2","ESP32-S2","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-S3-DevKitC-1","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-C3-DevKitM-1","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-C6-DevKitC-1","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Espressif","ESP32-H2-DevKitM-1","ESP32-H2","ESP32-H2","RISC-V",["Arduino","PlatformIO","ESPHome"],bluetooth=True,zigbee=True,thread=True,usb_connector="Micro-USB"),
    board("Espressif","ESP32-P4-Function-EV-Board","ESP32-P4","ESP32-P4","RISC-V",["ESP-IDF"],usb_connector="USB-C"),
    board("Generic","ESP8266 NodeMCU","ESP8266","ESP8266","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,usb_connector="Micro-USB"),
    board("Generic","Wemos D1 Mini (ESP8266)","ESP8266","ESP8266","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,usb_connector="Micro-USB"),
    board("Generic","ESP32-CAM AI-Thinker style","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Generic","ESP32 C3 Super Mini","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],flash_mb=4,ram_kb=400,gpio_count=13,wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Generic","ESP32-S3 Super Mini","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Generic","ESP32-C6 Super Mini","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Generic","ESP32-H2 Super Mini","ESP32-H2","ESP32-H2","RISC-V",["Arduino","PlatformIO","ESPHome"],bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Raspberry Pi","Raspberry Pi Zero","Raspberry Pi Zero","BCM2835"),
    board("Raspberry Pi","Raspberry Pi Zero W","Raspberry Pi Zero","BCM2835",wifi=True,bluetooth=True),
    board("Raspberry Pi","Raspberry Pi Zero 2 W","Raspberry Pi Zero","BCM2710A1",wifi=True,bluetooth=True),
    board("Raspberry Pi","Raspberry Pi 3 Model B+","Raspberry Pi","BCM2837B0",wifi=True,bluetooth=True),
    board("Raspberry Pi","Raspberry Pi 4 Model B","Raspberry Pi","BCM2711",wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Raspberry Pi","Raspberry Pi 5","Raspberry Pi","BCM2712",wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Raspberry Pi","Raspberry Pi Pico","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Raspberry Pi","Raspberry Pi Pico W","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Raspberry Pi","Raspberry Pi Pico 2","RP2350","RP2350","ARM Cortex-M33 / RISC-V",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Raspberry Pi","Raspberry Pi Pico 2 W","RP2350","RP2350","ARM Cortex-M33 / RISC-V",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Arduino","Uno R3","AVR","ATmega328P","AVR",["Arduino","PlatformIO"],usb_connector="USB-B"),
    board("Arduino","Uno R4 Minima","Renesas RA4M1","RA4M1","ARM Cortex-M4",["Arduino"],usb_connector="USB-C"),
    board("Arduino","Uno R4 WiFi","Renesas RA4M1","RA4M1 + ESP32-S3","ARM Cortex-M4",["Arduino"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Arduino","Nano","AVR","ATmega328P","AVR",["Arduino","PlatformIO"],usb_connector="Mini-USB"),
    board("Arduino","Nano Every","AVR","ATmega4809","AVR",["Arduino"],usb_connector="Micro-USB"),
    board("Arduino","Nano 33 IoT","SAMD21","SAMD21","ARM Cortex-M0+",["Arduino"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Arduino","Nano RP2040 Connect","RP2040","RP2040","ARM Cortex-M0+",["Arduino"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("Arduino","Nano ESP32","ESP32-S3","ESP32-S3","Xtensa",["Arduino","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Arduino","Mega 2560 Rev3","AVR","ATmega2560","AVR",["Arduino","PlatformIO"],usb_connector="USB-B"),
    board("Arduino","Leonardo","AVR","ATmega32U4","AVR",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Arduino","Micro","AVR","ATmega32U4","AVR",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Seeed Studio","XIAO ESP32C3","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Seeed Studio","XIAO ESP32C6","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Seeed Studio","XIAO ESP32S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Seeed Studio","XIAO RP2040","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("Seeed Studio","XIAO RP2350","RP2350","RP2350","ARM Cortex-M33 / RISC-V",["Arduino"],usb_connector="USB-C"),
    board("M5Stack","Atom Lite","ESP32","ESP32-PICO-D4","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","Atom S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","Core2","ESP32","ESP32-D0WDQ6-V3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","CoreS3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("M5Stack","Stamp C3","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Adafruit","Feather ESP32-S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Adafruit","QT Py ESP32-C3","ESP32-C3","ESP32-C3","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Adafruit","Feather RP2040","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("SparkFun","Pro Micro RP2040","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("PJRC","Teensy 4.0","Teensy","i.MX RT1062","ARM Cortex-M7",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("PJRC","Teensy 4.1","Teensy","i.MX RT1062","ARM Cortex-M7",["Arduino","PlatformIO"],usb_connector="Micro-USB"),
    board("Waveshare","ESP32-S3-Zero","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Waveshare","ESP32-C6-Zero","ESP32-C6","ESP32-C6","RISC-V",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,zigbee=True,thread=True,usb_connector="USB-C"),
    board("Waveshare","RP2040-Zero","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("Waveshare","RP2040-Plus","RP2040","RP2040","ARM Cortex-M0+",["Arduino","PlatformIO"],usb_connector="USB-C"),
    board("LilyGo","T-Display","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T-Display-S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T-Deck","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T-Beam","ESP32","ESP32","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("LilyGo","T3-S3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Heltec","WiFi LoRa 32 V3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Heltec","Wireless Stick Lite V3","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Olimex","ESP32-POE","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Olimex","ESP32-POE-ISO","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Olimex","ESP32-EVB","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True),
    board("Elecrow","CrowPanel ESP32 2.8in HMI","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Elecrow","CrowPanel ESP32 3.5in HMI","ESP32-S3","ESP32-S3","Xtensa",["Arduino","PlatformIO"],wifi=True,bluetooth=True,usb_connector="USB-C"),
    board("Generic","ESP32-2432S028R CYD","ESP32","ESP32","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="Micro-USB"),
    board("DFRobot","FireBeetle 2 ESP32-E","ESP32","ESP32-WROOM-32E","Xtensa",["Arduino","PlatformIO","ESPHome"],wifi=True,bluetooth=True,usb_connector="USB-C"),
]


# SBCs and compute modules are first-class boards.  Keep their richer Linux/PC
# attributes in specifications so the catalogue can evolve without forcing
# microcontroller-only columns onto every board type.
BOARD_DEFINITIONS += [
    board("Orange Pi", "Orange Pi 5 Plus", "Orange Pi 5", "Rockchip RK3588", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","cpu":"4× Cortex-A76 + 4× Cortex-A55","gpio_header":"40-pin","storage":["microSD","eMMC","M.2 NVMe"],"ethernet":"2× 2.5GbE","os_support":["Orange Pi OS","Ubuntu","Debian"]}),
    board("Orange Pi", "Orange Pi 5 Pro", "Orange Pi 5", "Rockchip RK3588S", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","gpio_header":"40-pin","storage":["microSD","eMMC","M.2"],"os_support":["Orange Pi OS","Ubuntu","Debian"]}),
    board("Orange Pi", "Orange Pi Zero 3", "Orange Pi Zero", "Allwinner H618", "ARM64", ["Linux"], usb_connector="USB-C", wifi=True, bluetooth=True, specifications={"board_type":"sbc","cpu":"4× Cortex-A53","form_factor":"compact SBC","storage":["microSD"],"os_support":["Orange Pi OS","Debian","Ubuntu"]}),
    board("Hardkernel", "ODROID-M1", "ODROID-M", "Rockchip RK3568B2", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","storage":["microSD","eMMC","M.2 NVMe","SATA"],"os_support":["Ubuntu","Debian"]}),
    board("Hardkernel", "ODROID-M1S", "ODROID-M", "Rockchip RK3566", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","storage":["microSD","eMMC","M.2 NVMe"],"os_support":["Ubuntu","Debian"]}),
    board("Hardkernel", "ODROID-M2", "ODROID-M", "Rockchip RK3588S2", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","cpu":"4× Cortex-A76 + 4× Cortex-A55","storage":["microSD","eMMC","M.2"],"os_support":["Ubuntu","Debian"]}),
    board("Hardkernel", "ODROID-C5", "ODROID-C", "Amlogic S905X5M", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","storage":["microSD","eMMC"],"os_support":["Ubuntu","Debian"]}),
    board("Hardkernel", "ODROID-N2+", "ODROID-N", "Amlogic S922X", "ARM64", ["Linux"], specifications={"board_type":"sbc","storage":["microSD","eMMC"],"os_support":["Ubuntu","Debian"]}),
    board("Hardkernel", "ODROID-H4", "ODROID-H", "Intel N97", "x86_64", ["Linux","Windows"], specifications={"board_type":"sbc","form_factor":"x86 SBC","storage":["SATA","M.2 NVMe"],"os_support":["Linux","Windows"]}),
    board("Hardkernel", "ODROID-H4 Plus", "ODROID-H", "Intel N97", "x86_64", ["Linux","Windows"], specifications={"board_type":"sbc","form_factor":"x86 SBC","storage":["SATA","M.2 NVMe"],"os_support":["Linux","Windows"]}),
    board("Radxa", "ROCK 3A", "ROCK 3", "Rockchip RK3568", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","gpio_header":"40-pin","os_support":["Debian","Ubuntu"]}),
    board("Radxa", "ROCK 4B+", "ROCK 4", "Rockchip RK3399", "ARM64", ["Linux"], usb_connector="USB-C", wifi=True, bluetooth=True, specifications={"board_type":"sbc","gpio_header":"40-pin","os_support":["Debian","Ubuntu"]}),
    board("Radxa", "ROCK 5A", "ROCK 5", "Rockchip RK3588S", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","cpu":"4× Cortex-A76 + 4× Cortex-A55","npu_tops":6,"os_support":["Debian","Ubuntu"]}),
    board("Radxa", "ROCK 5B", "ROCK 5", "Rockchip RK3588", "ARM64", ["Linux"], usb_connector="USB-C", specifications={"board_type":"sbc","cpu":"4× Cortex-A76 + 4× Cortex-A55","npu_tops":6,"ethernet":"2.5GbE","os_support":["Debian","Ubuntu"]}),
    board("Radxa", "ROCK 5C", "ROCK 5", "Rockchip RK3588S2", "ARM64", ["Linux"], usb_connector="USB-C", wifi=True, bluetooth=True, specifications={"board_type":"sbc","gpio_header":"40-pin","npu_tops":6,"ethernet":"GbE","os_support":["Debian","Ubuntu"]}),
    board("Radxa", "CM5", "Radxa CM", "Rockchip RK3588S2", "ARM64", ["Linux"], specifications={"board_type":"compute_module","form_factor":"56 × 41 mm SoM","npu_tops":6,"storage":["eMMC"],"carrier_required":True}),
    board("Banana Pi", "BPI-M5", "Banana Pi M", "Amlogic S905X3", "ARM64", ["Linux"], specifications={"board_type":"sbc","cpu":"4× Cortex-A55","ram_options":["4 GB"],"storage":["microSD","eMMC"],"ethernet":"GbE"}),
    board("Banana Pi", "BPI-M7", "Banana Pi M", "Rockchip RK3588", "ARM64", ["Linux"], wifi=True, specifications={"board_type":"sbc","cpu":"4× Cortex-A76 + 4× Cortex-A55","ram_options":["4 GB","8 GB","16 GB","32 GB"],"storage":["microSD","eMMC","M.2 NVMe"],"ethernet":"2× 2.5GbE","gpio_header":"40-pin","npu_tops":6}),
    board("BeagleBoard.org", "BeagleBone Black", "BeagleBone", "TI Sitara AM3358", "ARM Cortex-A8", ["Linux"], usb_connector="Mini-USB", specifications={"board_type":"sbc","gpio_header":"2× 46-pin","storage":["microSD","eMMC"],"os_support":["Debian"]}),
    board("BeagleBoard.org", "BeaglePlay", "Beagle", "TI Sitara AM625", "ARM64", ["Linux"], wifi=True, bluetooth=True, specifications={"board_type":"sbc","cpu":"4× Cortex-A53 + Cortex-M4F + PRU","ram_options":["2 GB"],"storage":["microSD","16 GB eMMC"],"ethernet":"GbE","expansion":["mikroBUS","Grove","Qwiic"]}),
    board("BeagleBoard.org", "BeagleY-AI", "Beagle", "TI AM67A", "ARM64", ["Linux"], specifications={"board_type":"sbc","form_factor":"Raspberry Pi 5 compatible","os_support":["Debian"]}),
    board("LattePanda", "LattePanda 3 Delta", "LattePanda", "Intel Celeron N5105", "x86_64", ["Windows","Linux","Arduino"], specifications={"board_type":"sbc","coprocessor":"ATmega32U4","storage":["eMMC","M.2"],"os_support":["Windows","Linux"]}),
    board("LattePanda", "LattePanda Sigma", "LattePanda", "Intel Core i5-1340P", "x86_64", ["Windows","Linux","Arduino"], specifications={"board_type":"sbc","cpu":"12 cores / 16 threads","coprocessor":"ATmega32U4","ram_options":["16 GB","32 GB"],"storage":["M.2 NVMe/SATA","SATA"],"ethernet":"2× 2.5GbE","gpio_header":"34-pin","os_support":["Windows 10/11","Ubuntu","Proxmox VE"]}),
    board("LattePanda", "LattePanda Mu", "LattePanda Mu", "Intel N100 / Core i3-N305", "x86_64", ["Windows","Linux"], specifications={"board_type":"compute_module","ram_options":["8 GB","16 GB"],"storage":["64 GB eMMC"],"carrier_required":True,"os_support":["Windows 10/11","Ubuntu"]}),
    board("NVIDIA", "Jetson Orin Nano Super Developer Kit", "Jetson Orin", "Jetson Orin Nano", "ARM64", ["JetPack","Linux"], specifications={"board_type":"sbc","cpu":"6× Cortex-A78AE","ai_performance":"67 TOPS","module_family":"Jetson Orin Nano/NX","os_support":["NVIDIA JetPack"]}),
    board("NVIDIA", "Jetson AGX Orin Developer Kit", "Jetson Orin", "Jetson AGX Orin", "ARM64", ["JetPack","Linux"], specifications={"board_type":"sbc","cpu":"12× Cortex-A78AE","ai_performance":"up to 275 TOPS","os_support":["NVIDIA JetPack"]}),
    board("NVIDIA", "Jetson Orin Nano 8GB", "Jetson Orin", "Jetson Orin Nano", "ARM64", ["JetPack","Linux"], specifications={"board_type":"compute_module","ram_options":["8 GB"],"ai_performance":"up to 67 TOPS","carrier_required":True}),
    board("NVIDIA", "Jetson Orin Nano 4GB", "Jetson Orin", "Jetson Orin Nano", "ARM64", ["JetPack","Linux"], specifications={"board_type":"compute_module","ram_options":["4 GB"],"ai_performance":"up to 34 TOPS","carrier_required":True}),
    board("NVIDIA", "Jetson Orin NX 8GB", "Jetson Orin", "Jetson Orin NX", "ARM64", ["JetPack","Linux"], specifications={"board_type":"compute_module","ram_options":["8 GB"],"ai_performance":"up to 117 TOPS","carrier_required":True}),
    board("NVIDIA", "Jetson Orin NX 16GB", "Jetson Orin", "Jetson Orin NX", "ARM64", ["JetPack","Linux"], specifications={"board_type":"compute_module","ram_options":["16 GB"],"ai_performance":"up to 157 TOPS","carrier_required":True}),
    board("NVIDIA", "Jetson AGX Orin 32GB", "Jetson Orin", "Jetson AGX Orin", "ARM64", ["JetPack","Linux"], specifications={"board_type":"compute_module","ram_options":["32 GB"],"ai_performance":"up to 241 TOPS","carrier_required":True}),
    board("NVIDIA", "Jetson AGX Orin 64GB", "Jetson Orin", "Jetson AGX Orin", "ARM64", ["JetPack","Linux"], specifications={"board_type":"compute_module","ram_options":["64 GB"],"ai_performance":"up to 275 TOPS","carrier_required":True}),
    board("Khadas", "Edge2 Maker Kit", "Khadas Edge", "Rockchip RK3588S2", "ARM64", ["Linux"], usb_connector="USB-C", wifi=True, specifications={"board_type":"sbc","cpu":"4× Cortex-A76 + 4× Cortex-A55","ram_options":["8 GB","16 GB"],"storage":["32/64 GB eMMC"],"npu_tops":6}),
    board("Khadas", "VIM4", "Khadas VIM", "Amlogic A311D2", "ARM64", ["Linux"], usb_connector="USB-C", wifi=True, bluetooth=True, specifications={"board_type":"sbc","storage":["eMMC","microSD"],"os_support":["Ubuntu","Android"]}),
]

# Classify the existing catalogue too, including the Raspberry Pi SBCs that
# pre-date this expansion.  Explicit definitions always win.
for _board in BOARD_DEFINITIONS:
    _specs = _board.setdefault("specifications", {})
    if "board_type" not in _specs:
        _name = _board["name"].lower()
        _maker = _board["manufacturer"]
        if _maker == "Raspberry Pi" and not ("pico" in _name):
            _specs["board_type"] = "sbc"
        else:
            _specs["board_type"] = "microcontroller"


CATEGORY_TREE = {
    "Passives": None,
    "Semiconductors": None,
    "LEDs & Lighting": None,
    "Displays": None,
    "Sensors": None,
    "Communications": None,
    "Audio": None,
    "Controls": None,
    "Power": None,
    "Relays & Switching": None,
    "Prototyping": None,
    "Connectors": None,
    "Storage": None,
    "Timing": None,
    "Motors & Drivers": None,
    "Cameras & Vision": None,
    "Logic & Level Shifting": None,
    "Mechanical & Thermal": None,
    "Test & Measurement": None,
    "Expansion Boards": None,
}


def component(category, name, part_number="", description="", **specifications):
    return {
        "category": category,
        "name": name,
        "part_number": part_number,
        "description": description,
        "specifications": specifications,
    }


COMPONENT_DEFINITIONS = [
    component("Passives","Resistor assortment 1/4W",type="resistor",power="0.25 W",package="through-hole"),
    component("Passives","220 ohm resistor","",type="resistor",value="220 Ω",power="0.25 W",package="through-hole"),
    component("Passives","1k ohm resistor","",type="resistor",value="1 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","4.7k ohm resistor","",type="resistor",value="4.7 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","10k ohm resistor","",type="resistor",value="10 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","100k ohm resistor","",type="resistor",value="100 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","Ceramic capacitor assortment","",type="capacitor",package="through-hole"),
    component("Passives","100nF ceramic capacitor","",type="capacitor",value="100 nF",package="through-hole"),
    component("Passives","10uF electrolytic capacitor","",type="capacitor",value="10 µF",package="radial"),
    component("Passives","100uF electrolytic capacitor","",type="capacitor",value="100 µF",package="radial"),
    component("Passives","470uF electrolytic capacitor","",type="capacitor",value="470 µF",package="radial"),

    component("Semiconductors","1N4148 signal diode","1N4148",type="diode",package="DO-35"),
    component("Semiconductors","1N4007 rectifier diode","1N4007",type="diode",package="DO-41"),
    component("Semiconductors","SS34 Schottky diode","SS34",type="diode",package="SMA"),
    component("Semiconductors","2N2222 NPN transistor","2N2222",type="transistor",package="TO-92"),
    component("Semiconductors","BC547 NPN transistor","BC547",type="transistor",package="TO-92"),
    component("Semiconductors","2N3904 NPN transistor","2N3904",type="transistor",package="TO-92"),
    component("Semiconductors","IRLZ44N logic-level N-MOSFET","IRLZ44N",type="mosfet",package="TO-220"),
    component("Semiconductors","AO3400A N-MOSFET","AO3400A",type="mosfet",package="SOT-23"),
    component("Semiconductors","PC817 optocoupler","PC817",type="optocoupler",package="DIP-4"),
    component("Semiconductors","AMS1117-3.3 regulator","AMS1117-3.3",type="regulator",output="3.3 V",package="SOT-223"),
    component("Semiconductors","L7805 5V regulator","L7805",type="regulator",output="5 V",package="TO-220"),

    component("LEDs & Lighting","5mm red LED","",type="led",colour="red",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm green LED","",type="led",colour="green",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm blue LED","",type="led",colour="blue",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm white LED","",type="led",colour="white",package="5 mm through-hole"),
    component("LEDs & Lighting","5mm RGB LED common cathode","",type="rgb-led",package="5 mm through-hole"),
    component("LEDs & Lighting","WS2812B addressable RGB LED","WS2812B",type="addressable-led",protocol="single-wire",voltage="5 V"),
    component("LEDs & Lighting","SK6812 RGBW addressable LED","SK6812",type="addressable-led",protocol="single-wire",voltage="5 V"),
    component("LEDs & Lighting","WS2812 8 LED ring","",type="led-ring",protocol="single-wire",led_count=8,voltage="5 V"),
    component("LEDs & Lighting","WS2812 12 LED ring","",type="led-ring",protocol="single-wire",led_count=12,voltage="5 V"),
    component("LEDs & Lighting","WS2812 16 LED ring","",type="led-ring",protocol="single-wire",led_count=16,voltage="5 V"),
    component("LEDs & Lighting","WS2812 24 LED ring","",type="led-ring",protocol="single-wire",led_count=24,voltage="5 V"),
    component("LEDs & Lighting","WS2812 8x8 RGB matrix","",type="led-matrix",protocol="single-wire",resolution="8x8",voltage="5 V"),
    component("LEDs & Lighting","WS2812B LED strip","",type="led-strip",protocol="single-wire",voltage="5 V"),

    component("Displays","SSD1306 0.96in OLED 128x64 I2C","SSD1306",type="oled",interface="I2C",resolution="128x64",voltage="3.3-5 V"),
    component("Displays","SH1106 1.3in OLED 128x64 I2C","SH1106",type="oled",interface="I2C",resolution="128x64"),
    component("Displays","SSD1327 1.5in OLED 128x128","SSD1327",type="oled",interface="I2C/SPI",resolution="128x128"),
    component("Displays","ST7735 1.8in TFT 160x128","ST7735",type="tft",interface="SPI",resolution="160x128"),
    component("Displays","ST7789 1.9in TFT 170x320","ST7789",type="tft",interface="SPI",resolution="170x320"),
    component("Displays","ILI9341 2.4in TFT 320x240","ILI9341",type="tft",interface="SPI",resolution="320x240"),
    component("Displays","ILI9488 3.5in TFT 480x320","ILI9488",type="tft",interface="SPI",resolution="480x320"),
    component("Displays","GC9A01 1.28in round TFT 240x240","GC9A01",type="round-tft",interface="SPI",resolution="240x240"),
    component("Displays","LCD1602 character display","HD44780",type="character-lcd",interface="parallel",resolution="16x2"),
    component("Displays","LCD2004 character display","HD44780",type="character-lcd",interface="parallel",resolution="20x4"),
    component("Displays","PCF8574 I2C LCD backpack","PCF8574",type="display-adapter",interface="I2C"),
    component("Displays","TM1637 4-digit 7-segment display","TM1637",type="7-segment",interface="2-wire"),
    component("Displays","MAX7219 8x8 LED matrix module","MAX7219",type="led-matrix",interface="SPI-like",resolution="8x8"),
    component("Displays","2.13in e-paper display module","",type="e-paper",interface="SPI"),

    component("Sensors","BME280 temperature/humidity/pressure sensor","BME280",type="environment",interface="I2C/SPI",measures=["temperature","humidity","pressure"]),
    component("Sensors","BMP280 pressure/temperature sensor","BMP280",type="environment",interface="I2C/SPI",measures=["temperature","pressure"]),
    component("Sensors","BMP388 precision pressure sensor","BMP388",type="environment",interface="I2C/SPI",measures=["temperature","pressure"]),
    component("Sensors","SHT31 temperature/humidity sensor","SHT31",type="environment",interface="I2C",measures=["temperature","humidity"]),
    component("Sensors","SHT40 temperature/humidity sensor","SHT40",type="environment",interface="I2C",measures=["temperature","humidity"]),
    component("Sensors","AHT20 temperature/humidity sensor","AHT20",type="environment",interface="I2C",measures=["temperature","humidity"]),
    component("Sensors","DHT22 temperature/humidity sensor","DHT22",type="environment",interface="single-wire",measures=["temperature","humidity"]),
    component("Sensors","DS18B20 waterproof temperature probe","DS18B20",type="temperature",interface="1-Wire"),
    component("Sensors","BH1750 light sensor","BH1750",type="light",interface="I2C"),
    component("Sensors","TSL2561 digital light sensor","TSL2561",type="light",interface="I2C"),
    component("Sensors","MPU6050 6-axis IMU","MPU6050",type="imu",interface="I2C",axes=6),
    component("Sensors","MPU9250 9-axis IMU","MPU9250",type="imu",interface="I2C/SPI",axes=9),
    component("Sensors","ADXL345 3-axis accelerometer","ADXL345",type="accelerometer",interface="I2C/SPI",axes=3),
    component("Sensors","VL53L0X time-of-flight distance sensor","VL53L0X",type="distance",interface="I2C"),
    component("Sensors","VL53L1X time-of-flight distance sensor","VL53L1X",type="distance",interface="I2C"),
    component("Sensors","HC-SR04 ultrasonic distance sensor","HC-SR04",type="distance",interface="trigger/echo",voltage="5 V"),
    component("Sensors","HC-SR501 PIR motion sensor","HC-SR501",type="motion",interface="digital"),
    component("Sensors","RCWL-0516 microwave motion sensor","RCWL-0516",type="motion",interface="digital"),
    component("Sensors","LD2410B mmWave presence sensor","LD2410B",type="presence",interface="UART/Bluetooth"),
    component("Sensors","LD2410C mmWave presence sensor","LD2410C",type="presence",interface="UART/Bluetooth"),
    component("Sensors","A3144 Hall effect sensor","A3144",type="magnetic",interface="digital"),
    component("Sensors","Magnetic reed switch","",type="magnetic",interface="digital"),
    component("Sensors","Capacitive soil moisture sensor v1.2","",type="soil-moisture",interface="analog"),
    component("Sensors","HX711 load-cell amplifier","HX711",type="weight",interface="2-wire"),
    component("Sensors","1kg load cell","",type="load-cell",capacity="1 kg"),
    component("Sensors","5kg load cell","",type="load-cell",capacity="5 kg"),
    component("Sensors","MQ-2 gas/smoke sensor module","MQ-2",type="gas",interface="analog/digital"),
    component("Sensors","MQ-135 air-quality sensor module","MQ-135",type="gas",interface="analog/digital"),
    component("Sensors","INA219 current/voltage monitor","INA219",type="power-monitor",interface="I2C"),
    component("Sensors","INA226 current/voltage monitor","INA226",type="power-monitor",interface="I2C"),
    component("Sensors","ACS712 current sensor module","ACS712",type="current",interface="analog"),
    component("Sensors","ADS1115 16-bit ADC module","ADS1115",type="adc",interface="I2C",resolution="16-bit"),

    component("Communications","HC-05 Bluetooth serial module","HC-05",type="bluetooth",interface="UART"),
    component("Communications","HC-06 Bluetooth serial module","HC-06",type="bluetooth",interface="UART"),
    component("Communications","nRF24L01+ 2.4GHz radio module","nRF24L01+",type="2.4ghz-radio",interface="SPI"),
    component("Communications","nRF24L01+ PA/LNA radio module","nRF24L01+",type="2.4ghz-radio",interface="SPI"),
    component("Communications","SX1278 LoRa module","SX1278",type="lora",interface="SPI"),
    component("Communications","RFM95W LoRa radio module","RFM95W",type="lora",interface="SPI"),
    component("Communications","W5500 Ethernet module","W5500",type="ethernet",interface="SPI"),
    component("Communications","ENC28J60 Ethernet module","ENC28J60",type="ethernet",interface="SPI"),
    component("Communications","MCP2515 CAN bus module","MCP2515",type="can",interface="SPI"),
    component("Communications","SN65HVD230 CAN transceiver module","SN65HVD230",type="can-transceiver",interface="CAN"),
    component("Communications","MAX485 RS-485 transceiver module","MAX485",type="rs485",interface="UART"),
    component("Communications","RC522 RFID reader module","MFRC522",type="rfid",interface="SPI"),
    component("Communications","PN532 NFC/RFID module","PN532",type="nfc",interface="I2C/SPI/UART"),
    component("Communications","CP2102 USB-to-UART module","CP2102",type="usb-serial",interface="USB/UART"),
    component("Communications","CH340G USB-to-UART module","CH340G",type="usb-serial",interface="USB/UART"),

    component("Audio","INMP441 I2S MEMS microphone module","INMP441",type="microphone",interface="I2S"),
    component("Audio","SPH0645 I2S MEMS microphone module","SPH0645",type="microphone",interface="I2S"),
    component("Audio","MAX98357A I2S amplifier module","MAX98357A",type="amplifier",interface="I2S"),
    component("Audio","NS4168 I2S amplifier module","NS4168",type="amplifier",interface="I2S"),
    component("Audio","PAM8403 stereo amplifier module","PAM8403",type="amplifier",interface="analog",power="2x3 W"),
    component("Audio","DFPlayer Mini MP3 module","DFPlayer Mini",type="audio-player",interface="UART"),
    component("Audio","Active piezo buzzer module","",type="buzzer",interface="digital"),
    component("Audio","Passive piezo buzzer","",type="buzzer",interface="PWM"),
    component("Audio","8 ohm 3W speaker","",type="speaker",impedance="8 Ω",power="3 W"),

    component("Controls","EC11 rotary encoder","EC11",type="rotary-encoder",interface="quadrature"),
    component("Controls","Momentary tactile push button","",type="button",interface="digital"),
    component("Controls","Illuminated momentary push button","",type="button",interface="digital"),
    component("Controls","SPST toggle switch","",type="switch"),
    component("Controls","Rocker switch","",type="switch"),
    component("Controls","10k potentiometer","",type="potentiometer",value="10 kΩ",interface="analog"),
    component("Controls","10k slide potentiometer","",type="potentiometer",value="10 kΩ",interface="analog"),
    component("Controls","PS2-style joystick module","",type="joystick",interface="analog/digital"),
    component("Controls","4x4 matrix keypad","",type="keypad",interface="matrix",keys=16),
    component("Controls","TTP223 capacitive touch module","TTP223",type="touch",interface="digital"),

    component("Power","LM2596 adjustable buck converter module","LM2596",type="buck",input="4-40 V",output="1.25-35 V"),
    component("Power","MP1584 mini adjustable buck converter","MP1584",type="buck",input="4.5-28 V"),
    component("Power","MT3608 boost converter module","MT3608",type="boost",input="2-24 V"),
    component("Power","XL4015 adjustable buck converter module","XL4015",type="buck",input="5-36 V"),
    component("Power","TP4056 USB-C Li-ion charger module","TP4056",type="battery-charger",connector="USB-C",cells="1S"),
    component("Power","TP4056 Micro-USB Li-ion charger module","TP4056",type="battery-charger",connector="Micro-USB",cells="1S"),
    component("Power","1S Li-ion protection/BMS module","",type="bms",cells="1S"),
    component("Power","AMS1117 3.3V regulator module","AMS1117-3.3",type="linear-regulator",output="3.3 V"),
    component("Power","USB-C PD trigger module","",type="usb-pd",connector="USB-C"),
    component("Power","DC barrel jack breakout","",type="power-connector",connector="5.5x2.1 mm"),

    component("Relays & Switching","5V single-channel relay module","",type="relay",channels=1,coil_voltage="5 V"),
    component("Relays & Switching","5V dual-channel relay module","",type="relay",channels=2,coil_voltage="5 V"),
    component("Relays & Switching","5V four-channel relay module","",type="relay",channels=4,coil_voltage="5 V"),
    component("Relays & Switching","Logic-level MOSFET switch module","",type="mosfet-switch",interface="digital/PWM"),

    component("Logic & Level Shifting","BSS138 4-channel bidirectional level shifter","BSS138",type="level-shifter",channels=4),
    component("Logic & Level Shifting","TXS0108E 8-channel level shifter","TXS0108E",type="level-shifter",channels=8),
    component("Logic & Level Shifting","74HC595 shift register","74HC595",type="shift-register",interface="SPI-like",bits=8),
    component("Logic & Level Shifting","74HC165 parallel-in shift register","74HC165",type="shift-register",interface="SPI-like",bits=8),
    component("Logic & Level Shifting","MCP23017 16-bit GPIO expander","MCP23017",type="gpio-expander",interface="I2C",gpio=16),
    component("Logic & Level Shifting","PCF8574 8-bit GPIO expander","PCF8574",type="gpio-expander",interface="I2C",gpio=8),

    component("Prototyping","830-point solderless breadboard","",type="breadboard",points=830),
    component("Prototyping","400-point solderless breadboard","",type="breadboard",points=400),
    component("Prototyping","170-point mini breadboard","",type="breadboard",points=170),
    component("Prototyping","2.54mm perfboard","",type="perfboard",pitch="2.54 mm"),
    component("Prototyping","Male header strip 2.54mm","",type="header",pitch="2.54 mm"),
    component("Prototyping","Female header strip 2.54mm","",type="header",pitch="2.54 mm"),
    component("Prototyping","Dupont jumper wire set M-M","",type="jumper-wire"),
    component("Prototyping","Dupont jumper wire set M-F","",type="jumper-wire"),
    component("Prototyping","Dupont jumper wire set F-F","",type="jumper-wire"),

    component("Connectors","Dupont crimp housing and pin kit","",type="connector",pitch="2.54 mm"),
    component("Connectors","JST-XH connector kit","JST-XH",type="connector",pitch="2.5 mm"),
    component("Connectors","JST-PH connector kit","JST-PH",type="connector",pitch="2.0 mm"),
    component("Connectors","JST-SH connector kit","JST-SH",type="connector",pitch="1.0 mm"),
    component("Connectors","2-pin screw terminal block","",type="terminal-block"),
    component("Connectors","3-pin screw terminal block","",type="terminal-block"),
    component("Connectors","XT30 connector pair","XT30",type="power-connector"),
    component("Connectors","XT60 connector pair","XT60",type="power-connector"),

    component("Storage","MicroSD SPI module","",type="flash-storage",interface="SPI"),
    component("Storage","Full-size SD card SPI module","",type="flash-storage",interface="SPI"),
    component("Storage","AT24C32 I2C EEPROM module","AT24C32",type="eeprom",interface="I2C",capacity="32 Kbit"),
    component("Storage","MB85RC256 I2C FRAM module","MB85RC256",type="fram",interface="I2C",capacity="256 Kbit"),

    component("Timing","DS3231 RTC module","DS3231",type="rtc",interface="I2C"),
    component("Timing","DS1307 RTC module","DS1307",type="rtc",interface="I2C"),
    component("Timing","PCF8563 RTC module","PCF8563",type="rtc",interface="I2C"),

    component("Motors & Drivers","SG90 9g micro servo","SG90",type="servo",interface="PWM"),
    component("Motors & Drivers","MG996R high-torque servo","MG996R",type="servo",interface="PWM"),
    component("Motors & Drivers","28BYJ-48 stepper motor","28BYJ-48",type="stepper"),
    component("Motors & Drivers","ULN2003 stepper driver board","ULN2003",type="motor-driver"),
    component("Motors & Drivers","A4988 stepper motor driver module","A4988",type="stepper-driver"),
    component("Motors & Drivers","DRV8825 stepper motor driver module","DRV8825",type="stepper-driver"),
    component("Motors & Drivers","TMC2209 stepper motor driver module","TMC2209",type="stepper-driver",interface="step/dir/UART"),
    component("Motors & Drivers","L298N dual H-bridge module","L298N",type="dc-motor-driver"),
    component("Motors & Drivers","TB6612FNG dual motor driver","TB6612FNG",type="dc-motor-driver"),
    component("Motors & Drivers","BTS7960 high-current motor driver","BTS7960",type="dc-motor-driver"),
    component("Motors & Drivers","PCA9685 16-channel PWM/servo driver","PCA9685",type="pwm-driver",interface="I2C",channels=16),

    component("Cameras & Vision","OV2640 camera module","OV2640",type="camera",resolution="2 MP"),
    component("Cameras & Vision","OV5640 camera module","OV5640",type="camera",resolution="5 MP"),

    component("Mechanical & Thermal","5V 40mm cooling fan","",type="fan",size="40 mm",voltage="5 V"),
    component("Mechanical & Thermal","12V 40mm cooling fan","",type="fan",size="40 mm",voltage="12 V"),
    component("Mechanical & Thermal","M2 heat-set insert assortment","",type="heat-set-insert",thread="M2"),
    component("Mechanical & Thermal","M3 heat-set insert assortment","",type="heat-set-insert",thread="M3"),
    component("Mechanical & Thermal","M3 screw assortment","",type="fastener",thread="M3"),
    component("Mechanical & Thermal","Neodymium magnet assortment","",type="magnet"),

    component("Test & Measurement","USB inline voltage/current meter","",type="power-meter",interface="USB"),
    component("Test & Measurement","Mini logic analyser 8-channel","",type="logic-analyser",channels=8),
    # Expanded maker-project catalogue: common starter-kit parts, prototyping staples,
    # frequently used sensor/breakout modules, power parts, interfaces and actuators.
    component("Passives","100 ohm resistor","",type="resistor",value="100 Ω",power="0.25 W",package="through-hole"),
    component("Passives","330 ohm resistor","",type="resistor",value="330 Ω",power="0.25 W",package="through-hole"),
    component("Passives","470 ohm resistor","",type="resistor",value="470 Ω",power="0.25 W",package="through-hole"),
    component("Passives","2.2k ohm resistor","",type="resistor",value="2.2 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","22k ohm resistor","",type="resistor",value="22 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","47k ohm resistor","",type="resistor",value="47 kΩ",power="0.25 W",package="through-hole"),
    component("Passives","1M ohm resistor","",type="resistor",value="1 MΩ",power="0.25 W",package="through-hole"),
    component("Passives","10M ohm resistor","",type="resistor",value="10 MΩ",power="0.25 W",package="through-hole"),
    component("Passives","10pF ceramic capacitor","",type="capacitor",value="10 pF",package="through-hole"),
    component("Passives","22pF ceramic capacitor","",type="capacitor",value="22 pF",package="through-hole"),
    component("Passives","1nF ceramic capacitor","",type="capacitor",value="1 nF",package="through-hole"),
    component("Passives","10nF ceramic capacitor","",type="capacitor",value="10 nF",package="through-hole"),
    component("Passives","1uF ceramic capacitor","",type="capacitor",value="1 µF",package="through-hole"),
    component("Passives","22uF electrolytic capacitor","",type="capacitor",value="22 µF",package="radial"),
    component("Passives","220uF electrolytic capacitor","",type="capacitor",value="220 µF",package="radial"),
    component("Passives","1000uF electrolytic capacitor","",type="capacitor",value="1000 µF",package="radial"),
    component("Passives","10k NTC thermistor","",type="thermistor",value="10 kΩ",interface="analog"),
    component("Passives","Photoresistor LDR","",type="photoresistor",interface="analog"),
    component("Passives","10uH power inductor","",type="inductor",value="10 µH"),
    component("Passives","100uH power inductor","",type="inductor",value="100 µH"),

    component("Semiconductors","1N5819 Schottky diode","1N5819",type="diode",package="DO-41"),
    component("Semiconductors","1N5408 rectifier diode","1N5408",type="diode",package="DO-201AD"),
    component("Semiconductors","5.1V Zener diode","1N4733A",type="zener-diode",voltage="5.1 V",package="DO-41"),
    component("Semiconductors","12V Zener diode","1N4742A",type="zener-diode",voltage="12 V",package="DO-41"),
    component("Semiconductors","2N3906 PNP transistor","2N3906",type="transistor",package="TO-92"),
    component("Semiconductors","BC557 PNP transistor","BC557",type="transistor",package="TO-92"),
    component("Semiconductors","S8050 NPN transistor","S8050",type="transistor",package="TO-92"),
    component("Semiconductors","S8550 PNP transistor","S8550",type="transistor",package="TO-92"),
    component("Semiconductors","TIP120 NPN Darlington transistor","TIP120",type="darlington",package="TO-220"),
    component("Semiconductors","2N7000 N-MOSFET","2N7000",type="mosfet",package="TO-92"),
    component("Semiconductors","IRF520 N-MOSFET","IRF520",type="mosfet",package="TO-220"),
    component("Semiconductors","IRFZ44N N-MOSFET","IRFZ44N",type="mosfet",package="TO-220"),
    component("Semiconductors","4N35 optocoupler","4N35",type="optocoupler",package="DIP-6"),
    component("Semiconductors","LM317 adjustable regulator","LM317",type="regulator",output="adjustable",package="TO-220"),
    component("Semiconductors","L7812 12V regulator","L7812",type="regulator",output="12 V",package="TO-220"),
    component("Semiconductors","LM358 dual op-amp","LM358",type="op-amp",channels=2,package="DIP-8"),
    component("Semiconductors","LM393 dual comparator","LM393",type="comparator",channels=2,package="DIP-8"),
    component("Semiconductors","TL431 adjustable shunt reference","TL431",type="voltage-reference",package="TO-92"),

    component("LEDs & Lighting","5mm yellow LED","",type="led",colour="yellow",package="5 mm through-hole"),
    component("LEDs & Lighting","3mm red LED","",type="led",colour="red",package="3 mm through-hole"),
    component("LEDs & Lighting","850nm infrared LED 5mm","",type="infrared-led",wavelength="850 nm",package="5 mm through-hole"),
    component("LEDs & Lighting","940nm infrared LED 5mm","",type="infrared-led",wavelength="940 nm",package="5 mm through-hole"),
    component("LEDs & Lighting","APA102 addressable RGB LED","APA102",type="addressable-led",protocol="SPI-like",voltage="5 V"),
    component("LEDs & Lighting","WS2812B 30 LED/m strip","",type="led-strip",protocol="single-wire",density="30 LED/m",voltage="5 V"),
    component("LEDs & Lighting","WS2812B 60 LED/m strip","",type="led-strip",protocol="single-wire",density="60 LED/m",voltage="5 V"),
    component("LEDs & Lighting","12V white LED strip","",type="led-strip",colour="white",voltage="12 V"),
    component("LEDs & Lighting","1W high-power white LED","",type="high-power-led",colour="white",power="1 W"),

    component("Displays","SSD1306 0.91in OLED 128x32 I2C","SSD1306",type="oled",interface="I2C",resolution="128x32"),
    component("Displays","ST7789 1.3in TFT 240x240","ST7789",type="tft",interface="SPI",resolution="240x240"),
    component("Displays","ST7789 2.0in TFT 240x320","ST7789",type="tft",interface="SPI",resolution="240x320"),
    component("Displays","ILI9341 2.8in TFT 320x240 touch","ILI9341",type="tft-touch",interface="SPI",resolution="320x240"),
    component("Displays","MAX7219 8-digit 7-segment module","MAX7219",type="7-segment",interface="SPI-like",digits=8),
    component("Displays","4-digit 7-segment display common cathode","",type="7-segment",digits=4),
    component("Displays","Single-digit 7-segment display common cathode","",type="7-segment",digits=1),
    component("Displays","HT16K33 4-digit 7-segment backpack","HT16K33",type="7-segment",interface="I2C",digits=4),
    component("Displays","MAX7219 4-in-1 8x8 LED matrix","MAX7219",type="led-matrix",interface="SPI-like",resolution="32x8"),
    component("Displays","0.56in 4-digit TM1637 display","TM1637",type="7-segment",interface="2-wire",digits=4),

    component("Sensors","DHT11 temperature/humidity sensor","DHT11",type="environment",interface="single-wire",measures=["temperature","humidity"]),
    component("Sensors","TMP36 analog temperature sensor","TMP36",type="temperature",interface="analog"),
    component("Sensors","LM35 analog temperature sensor","LM35",type="temperature",interface="analog"),
    component("Sensors","MAX6675 K-type thermocouple module","MAX6675",type="temperature",interface="SPI",sensor="K-type thermocouple"),
    component("Sensors","MAX31855 K-type thermocouple module","MAX31855",type="temperature",interface="SPI",sensor="K-type thermocouple"),
    component("Sensors","MAX31865 PT100/PT1000 RTD module","MAX31865",type="temperature",interface="SPI",sensor="RTD"),
    component("Sensors","BME680 environmental/gas sensor","BME680",type="environment",interface="I2C/SPI",measures=["temperature","humidity","pressure","gas"]),
    component("Sensors","BME688 environmental/gas sensor","BME688",type="environment",interface="I2C/SPI",measures=["temperature","humidity","pressure","gas"]),
    component("Sensors","SCD40 CO2 temperature/humidity sensor","SCD40",type="air-quality",interface="I2C",measures=["CO2","temperature","humidity"]),
    component("Sensors","SCD41 CO2 temperature/humidity sensor","SCD41",type="air-quality",interface="I2C",measures=["CO2","temperature","humidity"]),
    component("Sensors","CCS811 air-quality sensor","CCS811",type="air-quality",interface="I2C",measures=["eCO2","TVOC"]),
    component("Sensors","SGP30 air-quality sensor","SGP30",type="air-quality",interface="I2C",measures=["eCO2","TVOC"]),
    component("Sensors","SGP40 VOC sensor","SGP40",type="air-quality",interface="I2C",measures=["VOC"]),
    component("Sensors","PMS5003 particulate matter sensor","PMS5003",type="air-quality",interface="UART",measures=["PM1.0","PM2.5","PM10"]),
    component("Sensors","Photoresistor light sensor module","",type="light",interface="analog/digital"),
    component("Sensors","Phototransistor light sensor","",type="light",interface="analog"),
    component("Sensors","TCS34725 RGB colour sensor","TCS34725",type="colour",interface="I2C"),
    component("Sensors","APDS-9960 gesture/proximity sensor","APDS-9960",type="gesture-proximity",interface="I2C"),
    component("Sensors","QMC5883L 3-axis magnetometer","QMC5883L",type="magnetometer",interface="I2C",axes=3),
    component("Sensors","BNO055 9-axis absolute orientation sensor","BNO055",type="imu",interface="I2C/UART",axes=9),
    component("Sensors","ICM-20948 9-axis IMU","ICM-20948",type="imu",interface="I2C/SPI",axes=9),
    component("Sensors","LSM6DS3 6-axis IMU","LSM6DS3",type="imu",interface="I2C/SPI",axes=6),
    component("Sensors","AS5600 magnetic rotary position sensor","AS5600",type="magnetic-angle",interface="I2C/analog"),
    component("Sensors","MPR121 12-channel capacitive touch sensor","MPR121",type="touch",interface="I2C",channels=12),
    component("Sensors","FSR force-sensitive resistor","",type="force",interface="analog"),
    component("Sensors","Flex sensor 2.2in","",type="flex",interface="analog"),
    component("Sensors","SW-420 vibration sensor module","SW-420",type="vibration",interface="digital"),
    component("Sensors","Tilt ball switch sensor","",type="tilt",interface="digital"),
    component("Sensors","IR obstacle avoidance sensor module","",type="proximity",interface="digital"),
    component("Sensors","VS1838B 38kHz IR receiver","VS1838B",type="infrared-receiver",interface="digital",frequency="38 kHz"),
    component("Sensors","Flame sensor module","",type="flame",interface="analog/digital"),
    component("Sensors","Rain detection sensor module","",type="rain",interface="analog/digital"),
    component("Sensors","Water level sensor module","",type="water-level",interface="analog"),
    component("Sensors","Water leak sensor module","",type="water-leak",interface="digital"),
    component("Sensors","YF-S201 water flow sensor","YF-S201",type="flow",interface="pulse"),
    component("Sensors","Sound detection microphone module","",type="sound-level",interface="analog/digital"),
    component("Sensors","HX711 with 20kg load cell","HX711",type="weight",interface="2-wire",capacity="20 kg"),

    component("Communications","NEO-6M GPS module","NEO-6M",type="gnss",interface="UART"),
    component("Communications","NEO-M8N GPS/GNSS module","NEO-M8N",type="gnss",interface="UART/I2C"),
    component("Communications","SIM800L GSM/GPRS module","SIM800L",type="cellular",interface="UART"),
    component("Communications","SIM7600 4G LTE module","SIM7600",type="cellular",interface="USB/UART"),
    component("Communications","ESP-01 ESP8266 Wi-Fi module","ESP-01",type="wifi",interface="UART"),
    component("Communications","CC1101 sub-GHz radio module","CC1101",type="sub-ghz-radio",interface="SPI"),
    component("Communications","HC-12 433MHz serial radio module","HC-12",type="sub-ghz-radio",interface="UART"),
    component("Communications","E32 LoRa UART module","E32",type="lora",interface="UART"),
    component("Communications","XBee Series 2 Zigbee module","XBee Series 2",type="zigbee",interface="UART"),
    component("Communications","MAX3232 RS-232 transceiver module","MAX3232",type="rs232",interface="UART"),
    component("Communications","FT232RL USB-to-UART module","FT232RL",type="usb-serial",interface="USB/UART"),
    component("Communications","USB-to-RS485 adapter module","",type="usb-rs485",interface="USB/RS-485"),

    component("Audio","MAX9814 microphone amplifier module","MAX9814",type="microphone-amplifier",interface="analog"),
    component("Audio","MAX4466 electret microphone amplifier","MAX4466",type="microphone-amplifier",interface="analog"),
    component("Audio","Electret microphone capsule","",type="microphone",interface="analog"),
    component("Audio","PAM8302 mono amplifier module","PAM8302",type="amplifier",interface="analog",power="2.5 W"),
    component("Audio","MAX98306 stereo amplifier module","MAX98306",type="amplifier",interface="analog"),
    component("Audio","4 ohm 3W speaker","",type="speaker",impedance="4 Ω",power="3 W"),
    component("Audio","8 ohm 1W speaker","",type="speaker",impedance="8 Ω",power="1 W"),

    component("Controls","6x6mm tactile push button","",type="button",interface="digital",package="6x6 mm"),
    component("Controls","12mm tactile push button","",type="button",interface="digital",package="12 mm"),
    component("Controls","SPDT slide switch","",type="switch"),
    component("Controls","SPDT microswitch with lever","",type="microswitch"),
    component("Controls","Roller lever limit switch","",type="limit-switch"),
    component("Controls","8-position DIP switch","",type="dip-switch",positions=8),
    component("Controls","1k potentiometer","",type="potentiometer",value="1 kΩ",interface="analog"),
    component("Controls","100k potentiometer","",type="potentiometer",value="100 kΩ",interface="analog"),
    component("Controls","10k trimmer potentiometer","",type="trimmer",value="10 kΩ",interface="analog"),
    component("Controls","3x4 matrix keypad","",type="keypad",interface="matrix",keys=12),
    component("Controls","MX-compatible mechanical key switch","",type="key-switch",interface="digital"),
    component("Controls","Arcade push button","",type="button",interface="digital"),

    component("Power","XL6009 adjustable boost converter module","XL6009",type="boost",input="3-32 V"),
    component("Power","LM2596 fixed 5V buck converter module","LM2596",type="buck",output="5 V"),
    component("Power","5V to 3.3V regulator module","",type="linear-regulator",input="5 V",output="3.3 V"),
    component("Power","2S Li-ion protection/BMS module","",type="bms",cells="2S"),
    component("Power","3S Li-ion protection/BMS module","",type="bms",cells="3S"),
    component("Power","18650 single-cell battery holder","",type="battery-holder",cells=1,battery="18650"),
    component("Power","18650 dual-cell battery holder","",type="battery-holder",cells=2,battery="18650"),
    component("Power","2xAA battery holder","",type="battery-holder",cells=2,battery="AA"),
    component("Power","4xAA battery holder","",type="battery-holder",cells=4,battery="AA"),
    component("Power","9V PP3 battery snap","",type="battery-connector",battery="9V PP3"),
    component("Power","USB-C power breakout board","",type="power-breakout",connector="USB-C"),
    component("Power","Micro-USB power breakout board","",type="power-breakout",connector="Micro-USB"),
    component("Power","Resettable polyfuse assortment","",type="polyfuse"),
    component("Power","Mini blade fuse holder","",type="fuse-holder"),

    component("Relays & Switching","12V single-channel relay module","",type="relay",channels=1,coil_voltage="12 V"),
    component("Relays & Switching","5V eight-channel relay module","",type="relay",channels=8,coil_voltage="5 V"),
    component("Relays & Switching","5V solid-state relay module","",type="solid-state-relay",control_voltage="5 V"),
    component("Relays & Switching","SSR-40DA solid-state relay","SSR-40DA",type="solid-state-relay"),
    component("Relays & Switching","Optocoupled AC triac switch module","",type="triac-switch",interface="digital"),
    component("Relays & Switching","Dual logic-level MOSFET switch module","",type="mosfet-switch",channels=2,interface="digital/PWM"),

    component("Logic & Level Shifting","74HC00 quad NAND gate","74HC00",type="logic-gate",gates=4,package="DIP-14"),
    component("Logic & Level Shifting","74HC04 hex inverter","74HC04",type="logic-gate",gates=6,package="DIP-14"),
    component("Logic & Level Shifting","74HC08 quad AND gate","74HC08",type="logic-gate",gates=4,package="DIP-14"),
    component("Logic & Level Shifting","74HC14 Schmitt-trigger inverter","74HC14",type="logic-gate",gates=6,package="DIP-14"),
    component("Logic & Level Shifting","74HC32 quad OR gate","74HC32",type="logic-gate",gates=4,package="DIP-14"),
    component("Logic & Level Shifting","74HC86 quad XOR gate","74HC86",type="logic-gate",gates=4,package="DIP-14"),
    component("Logic & Level Shifting","74HC138 3-to-8 decoder","74HC138",type="decoder",outputs=8,package="DIP-16"),
    component("Logic & Level Shifting","74HC4051 8-channel analog multiplexer","74HC4051",type="multiplexer",channels=8,package="DIP-16"),
    component("Logic & Level Shifting","CD4017 decade counter","CD4017",type="counter",outputs=10,package="DIP-16"),
    component("Logic & Level Shifting","CD4093 quad Schmitt NAND gate","CD4093",type="logic-gate",gates=4,package="DIP-14"),
    component("Logic & Level Shifting","PCA9306 bidirectional I2C level shifter","PCA9306",type="level-shifter",channels=2,interface="I2C"),
    component("Logic & Level Shifting","74AHCT125 quad level shifter/buffer","74AHCT125",type="buffer-level-shifter",channels=4),

    component("Prototyping","Stripboard 2.54mm pitch","",type="stripboard",pitch="2.54 mm"),
    component("Prototyping","Solderable breadboard PCB","",type="prototype-pcb",pitch="2.54 mm"),
    component("Prototyping","Right-angle male header 2.54mm","",type="header",pitch="2.54 mm"),
    component("Prototyping","Stacking female header 2.54mm","",type="header",pitch="2.54 mm"),
    component("Prototyping","Pogo pin assortment","",type="pogo-pin"),
    component("Prototyping","PCB test-point loop assortment","",type="test-point"),

    component("Connectors","JST-SM 2-pin connector pair","JST-SM",type="connector",pins=2),
    component("Connectors","JST-SM 3-pin connector pair","JST-SM",type="connector",pins=3),
    component("Connectors","JST-SM 4-pin connector pair","JST-SM",type="connector",pins=4),
    component("Connectors","USB-C female breakout connector","",type="connector",connector="USB-C"),
    component("Connectors","Micro-USB female breakout connector","",type="connector",connector="Micro-USB"),
    component("Connectors","USB-A female breakout connector","",type="connector",connector="USB-A"),
    component("Connectors","5.5x2.1mm DC barrel jack panel socket","",type="power-connector",connector="5.5x2.1 mm"),
    component("Connectors","5.5x2.1mm DC barrel plug","",type="power-connector",connector="5.5x2.1 mm"),
    component("Connectors","GX12-4 aviation connector pair","GX12-4",type="connector",pins=4),
    component("Connectors","4-pin screw terminal block","",type="terminal-block",pins=4),
    component("Connectors","Lever wire connector 2-way","",type="wire-connector",ways=2),
    component("Connectors","Lever wire connector 3-way","",type="wire-connector",ways=3),

    component("Storage","W25Q32 SPI flash module","W25Q32",type="flash-storage",interface="SPI",capacity="32 Mbit"),
    component("Storage","W25Q64 SPI flash module","W25Q64",type="flash-storage",interface="SPI",capacity="64 Mbit"),
    component("Storage","AT24C256 I2C EEPROM module","AT24C256",type="eeprom",interface="I2C",capacity="256 Kbit"),

    component("Timing","NE555 timer IC","NE555",type="timer",package="DIP-8"),
    component("Timing","32.768kHz watch crystal","",type="crystal",frequency="32.768 kHz"),
    component("Timing","8MHz crystal","",type="crystal",frequency="8 MHz"),
    component("Timing","16MHz crystal","",type="crystal",frequency="16 MHz"),

    component("Motors & Drivers","NEMA 17 bipolar stepper motor","",type="stepper",size="NEMA 17"),
    component("Motors & Drivers","TT 3-6V geared DC motor","",type="gearmotor",voltage="3-6 V"),
    component("Motors & Drivers","N20 micro metal gearmotor","",type="gearmotor"),
    component("Motors & Drivers","3-6V hobby DC motor","",type="dc-motor",voltage="3-6 V"),
    component("Motors & Drivers","Coin vibration motor","",type="vibration-motor"),
    component("Motors & Drivers","5V push-pull solenoid","",type="solenoid",voltage="5 V"),
    component("Motors & Drivers","12V push-pull solenoid","",type="solenoid",voltage="12 V"),
    component("Motors & Drivers","L293D dual H-bridge IC","L293D",type="dc-motor-driver",package="DIP-16"),
    component("Motors & Drivers","SN754410 dual H-bridge IC","SN754410",type="dc-motor-driver",package="DIP-16"),
    component("Motors & Drivers","DRV8833 dual motor driver module","DRV8833",type="dc-motor-driver"),
    component("Motors & Drivers","TMC2208 stepper motor driver module","TMC2208",type="stepper-driver",interface="step/dir/UART"),

    component("Cameras & Vision","OV7670 VGA camera module","OV7670",type="camera",resolution="640x480"),
    component("Cameras & Vision","GC2145 2MP camera module","GC2145",type="camera",resolution="2 MP"),

    component("Mechanical & Thermal","5V 30mm cooling fan","",type="fan",size="30 mm",voltage="5 V"),
    component("Mechanical & Thermal","12V 60mm cooling fan","",type="fan",size="60 mm",voltage="12 V"),
    component("Mechanical & Thermal","M2.5 heat-set insert assortment","",type="heat-set-insert",thread="M2.5"),
    component("Mechanical & Thermal","M2 screw assortment","",type="fastener",thread="M2"),
    component("Mechanical & Thermal","M2.5 screw assortment","",type="fastener",thread="M2.5"),
    component("Mechanical & Thermal","M4 screw assortment","",type="fastener",thread="M4"),
    component("Mechanical & Thermal","M3 nylon standoff assortment","",type="standoff",thread="M3"),
    component("Mechanical & Thermal","M2.5 brass standoff assortment","",type="standoff",thread="M2.5"),
    component("Mechanical & Thermal","608ZZ ball bearing","608ZZ",type="bearing",dimensions="8x22x7 mm"),
    component("Mechanical & Thermal","Mini heatsink assortment","",type="heatsink"),

    component("Test & Measurement","USB-C inline voltage/current meter","",type="power-meter",interface="USB-C"),
    component("Test & Measurement","INA3221 3-channel power monitor module","INA3221",type="power-monitor",interface="I2C",channels=3),

]


# Host-specific add-on boards live in Components rather than masquerading as
# independently programmable boards.  Compatibility metadata is deliberately
# structured for future wiring/stacking validation.
COMPONENT_DEFINITIONS += [
    component("Expansion Boards","Raspberry Pi Sense HAT","",type="hat",manufacturer="Raspberry Pi",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",interfaces=["I2C","GPIO"],stackable=False),
    component("Expansion Boards","Raspberry Pi PoE+ HAT","",type="hat",manufacturer="Raspberry Pi",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",function="Power over Ethernet"),
    component("Expansion Boards","Raspberry Pi M.2 HAT+","",type="hat",manufacturer="Raspberry Pi",host_family="Raspberry Pi 5",host_interface="PCIe FFC",function="M.2 NVMe storage"),
    component("Expansion Boards","Adafruit Motor HAT for Raspberry Pi","",type="hat",manufacturer="Adafruit",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",interfaces=["I2C"],function="DC/stepper motor control"),
    component("Expansion Boards","Adafruit 16-Channel PWM/Servo HAT","",type="hat",manufacturer="Adafruit",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",interfaces=["I2C"],function="PWM/servo control"),
    component("Expansion Boards","Pimoroni Enviro pHAT","",type="phat",manufacturer="Pimoroni",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",interfaces=["I2C","SPI","ADC"]),
    component("Expansion Boards","Arduino Ethernet Shield","",type="shield",manufacturer="Arduino",host_family="Arduino Uno/Mega",host_interface="Arduino shield headers",interfaces=["SPI"],function="Ethernet"),
    component("Expansion Boards","Arduino Motor Shield Rev3","",type="shield",manufacturer="Arduino",host_family="Arduino Uno/Mega",host_interface="Arduino shield headers",function="DC/stepper motor control"),
    component("Expansion Boards","Arduino Proto Shield Rev3","",type="shield",manufacturer="Arduino",host_family="Arduino Uno",host_interface="Arduino shield headers",function="Prototyping"),
    component("Expansion Boards","Adafruit FeatherWing OLED","",type="featherwing",manufacturer="Adafruit",host_family="Adafruit Feather",host_interface="Feather headers",interfaces=["I2C"],function="OLED display"),
    component("Expansion Boards","Adafruit Motor FeatherWing","",type="featherwing",manufacturer="Adafruit",host_family="Adafruit Feather",host_interface="Feather headers",interfaces=["I2C"],function="DC/stepper motor control"),
    component("Expansion Boards","SparkFun Qwiic HAT for Raspberry Pi","",type="hat",manufacturer="SparkFun",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",interfaces=["I2C","Qwiic"],function="Qwiic expansion"),
    component("Expansion Boards","Seeed Grove Base HAT for Raspberry Pi","",type="hat",manufacturer="Seeed Studio",host_family="Raspberry Pi 40-pin",host_interface="40-pin GPIO",interfaces=["I2C","UART","GPIO","PWM","ADC"],function="Grove expansion"),
    component("Expansion Boards","Radxa 25W PoE+ HAT","",type="hat",manufacturer="Radxa",host_family="Radxa ROCK",host_interface="GPIO header",function="Power over Ethernet",compatible_hosts=["ROCK 5B","ROCK 5C"]),
    component("Expansion Boards","Radxa Penta SATA HAT","",type="hat",manufacturer="Radxa",host_family="Radxa ROCK",host_interface="PCIe/FPC",function="Five-port SATA expansion",compatible_hosts=["ROCK 5C"]),
    component("Expansion Boards","ODROID M.2 4×1 Card","",type="expansion-board",manufacturer="Hardkernel",host_family="ODROID H",host_interface="M.2",function="Four M.2 PCIe Gen3 x1 slots",compatible_hosts=["ODROID-H4 series"]),
]
