[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/app/run/supervisord.pid
user=root

[program:web]
command=gosu makervault gunicorn makervault.wsgi:application --bind 0.0.0.0:8000 --workers %(ENV_WEB_CONCURRENCY)s --timeout %(ENV_GUNICORN_TIMEOUT)s --access-logfile - --error-logfile -
directory=/app/backend
autostart=true
autorestart=true
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=gosu makervault celery -A makervault worker --loglevel=INFO --concurrency=%(ENV_CELERY_CONCURRENCY)s
directory=/app/backend
autostart=true
autorestart=true
startretries=5
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
