# Generated for MakerVault v0.1 initial schema.
import uuid
import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(name="CatalogSource", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=200)),
            ("source_type", models.CharField(choices=[("manual","Manual"),("espboards","ESPBoards.dev"),("spoolmandb","SpoolmanDB"),("filamentprofiles","3D Filament Profiles"),("filamentsdb","FilamentsDB"),("amazon","Amazon"),("aliexpress","AliExpress"),("github","GitHub"),("gitlab","GitLab"),("manufacturer","Manufacturer"),("generic","Generic URL")], default="manual", max_length=32)),
            ("url", models.URLField(blank=True)), ("external_id", models.CharField(blank=True, max_length=255)),
            ("last_checked_at", models.DateTimeField(blank=True, null=True)), ("raw_metadata", models.JSONField(blank=True, default=dict)),
        ]),
        migrations.CreateModel(name="Manufacturer", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=200, unique=True)), ("website", models.URLField(blank=True)),
            ("logo", models.ImageField(blank=True, null=True, upload_to="manufacturers/")),
        ], options={"ordering":["name"]}),
        migrations.CreateModel(name="ComponentCategory", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=120)), ("slug", models.SlugField(max_length=140, unique=True)),
            ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="core.componentcategory")),
        ], options={"verbose_name_plural":"Component categories", "ordering":["name"]}),
        migrations.CreateModel(name="Project", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
            ("status", models.CharField(choices=[("idea","Idea"),("planning","Planning"),("active","Active"),("paused","Paused"),("complete","Complete"),("archived","Archived")], default="idea", max_length=20)),
            ("summary", models.CharField(blank=True, max_length=500)), ("description", models.TextField(blank=True)),
            ("cover_image", models.ImageField(blank=True, null=True, upload_to="projects/covers/")),
            ("started_on", models.DateField(blank=True, null=True)), ("completed_on", models.DateField(blank=True, null=True)),
            ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="makervault_projects", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering":["-updated_at"]}),
        migrations.CreateModel(name="Printer", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("model", models.CharField(max_length=255)), ("serial_number", models.CharField(blank=True, max_length=255)),
            ("location", models.CharField(blank=True, max_length=255)), ("build_volume_x_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ("build_volume_y_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)), ("build_volume_z_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ("nozzle_mm", models.DecimalField(decimal_places=2, default=0.4, max_digits=5)), ("profile_data", models.JSONField(blank=True, default=dict)), ("notes", models.TextField(blank=True)),
            ("manufacturer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="printers", to="core.manufacturer")),
        ], options={"ordering":["name"]}),
        migrations.CreateModel(name="BoardModel", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
            ("family", models.CharField(blank=True, max_length=120)), ("variant", models.CharField(blank=True, max_length=120)), ("description", models.TextField(blank=True)),
            ("image", models.ImageField(blank=True, null=True, upload_to="boards/catalog/")), ("mcu", models.CharField(blank=True, max_length=120)), ("architecture", models.CharField(blank=True, max_length=120)),
            ("flash_mb", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)), ("psram_mb", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ("ram_kb", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("gpio_count", models.PositiveSmallIntegerField(blank=True, null=True)),
            ("wifi", models.BooleanField(default=False)), ("bluetooth", models.BooleanField(default=False)), ("zigbee", models.BooleanField(default=False)), ("thread", models.BooleanField(default=False)),
            ("usb_connector", models.CharField(blank=True, max_length=80)), ("dimensions_mm", models.JSONField(blank=True, default=dict)), ("specifications", models.JSONField(blank=True, default=dict)), ("pinout", models.JSONField(blank=True, default=dict)),
            ("manufacturer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="boards", to="core.manufacturer")),
            ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="boards", to="core.catalogsource")),
        ], options={"ordering":["manufacturer__name","name"]}),
        migrations.AddConstraint(model_name="boardmodel", constraint=models.UniqueConstraint(fields=("manufacturer","name","variant"), name="unique_board_variant")),
        migrations.CreateModel(name="BoardCompatibility", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("platform", models.CharField(max_length=80)), ("support_level", models.CharField(choices=[("full","Full"),("partial","Partial"),("experimental","Experimental"),("unknown","Unknown"),("no","Not supported")], default="unknown", max_length=20)),
            ("notes", models.TextField(blank=True)), ("config_template", models.TextField(blank=True)), ("source_url", models.URLField(blank=True)),
            ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="compatibility", to="core.boardmodel")),
        ], options={"ordering":["platform"]}),
        migrations.AddConstraint(model_name="boardcompatibility", constraint=models.UniqueConstraint(fields=("board","platform"), name="unique_board_platform")),
        migrations.CreateModel(name="ComponentModel", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("part_number", models.CharField(blank=True, max_length=160)), ("description", models.TextField(blank=True)),
            ("image", models.ImageField(blank=True, null=True, upload_to="components/catalog/")), ("specifications", models.JSONField(blank=True, default=dict)),
            ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="components", to="core.componentcategory")),
            ("manufacturer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="components", to="core.manufacturer")),
            ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="components", to="core.catalogsource")),
        ], options={"ordering":["name"]}),
        migrations.CreateModel(name="FilamentProduct", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("material", models.CharField(max_length=80)), ("color_name", models.CharField(blank=True, max_length=120)), ("color_hex", models.CharField(blank=True, max_length=9)),
            ("diameter_mm", models.DecimalField(decimal_places=2, default=1.75, max_digits=5)), ("density_g_cm3", models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ("nominal_weight_g", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("empty_spool_weight_g", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ("nozzle_temp_min_c", models.SmallIntegerField(blank=True, null=True)), ("nozzle_temp_max_c", models.SmallIntegerField(blank=True, null=True)), ("bed_temp_min_c", models.SmallIntegerField(blank=True, null=True)), ("bed_temp_max_c", models.SmallIntegerField(blank=True, null=True)),
            ("drying_temp_c", models.SmallIntegerField(blank=True, null=True)), ("drying_time_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ("image", models.ImageField(blank=True, null=True, upload_to="filament/catalog/")), ("profile_data", models.JSONField(blank=True, default=dict)),
            ("manufacturer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filaments", to="core.manufacturer")),
            ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="filaments", to="core.catalogsource")),
        ], options={"ordering":["manufacturer__name","name","color_name"]}),
        migrations.CreateModel(name="InventoryItem", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("inventory_id", models.CharField(max_length=40, unique=True)), ("item_type", models.CharField(choices=[("board","Board"),("component","Component"),("tool","Tool / asset"),("printed_part","Printed part"),("other","Other")], max_length=20)),
            ("custom_name", models.CharField(blank=True, max_length=255)), ("quantity", models.DecimalField(decimal_places=3, default=1, max_digits=12)), ("status", models.CharField(choices=[("available","Available"),("in_use","In use"),("reserved","Reserved"),("repair","Needs repair"),("retired","Retired")], default="available", max_length=20)),
            ("location", models.CharField(blank=True, max_length=255)), ("serial_number", models.CharField(blank=True, max_length=255)), ("purchase_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ("currency", models.CharField(default="GBP", max_length=3)), ("supplier", models.CharField(blank=True, max_length=255)), ("purchase_url", models.URLField(blank=True)), ("purchased_on", models.DateField(blank=True, null=True)),
            ("image", models.ImageField(blank=True, null=True, upload_to="inventory/")), ("notes", models.TextField(blank=True)),
            ("board", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="inventory_items", to="core.boardmodel")),
            ("component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="inventory_items", to="core.componentmodel")),
            ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_items", to="core.project")),
        ], options={"ordering":["inventory_id"]}),
        migrations.CreateModel(name="BOMItem", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("custom_name", models.CharField(blank=True, max_length=255)), ("quantity", models.DecimalField(decimal_places=3, default=1, max_digits=12)), ("unit", models.CharField(default="item", max_length=40)),
            ("unit_cost", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)), ("currency", models.CharField(default="GBP", max_length=3)), ("notes", models.TextField(blank=True)),
            ("board", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bom_items", to="core.boardmodel")),
            ("component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bom_items", to="core.componentmodel")),
            ("inventory_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bom_items", to="core.inventoryitem")),
            ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bom_items", to="core.project")),
        ], options={"ordering":["created_at"]}),
        migrations.CreateModel(name="FileAsset", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("category", models.CharField(choices=[("image","Image"),("wiring","Wiring / schematic"),("firmware","Firmware"),("source","Source code"),("binary","Executable / binary"),("document","Document"),("cad","CAD"),("mesh","STL / mesh"),("slicer","3MF / slicer project"),("pcb","PCB"),("archive","Archive"),("other","Other")], default="other", max_length=20)),
            ("file", models.FileField(upload_to="files/%Y/%m/", validators=[core.validators.validate_maker_file])), ("version", models.CharField(blank=True, max_length=80)), ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
            ("description", models.TextField(blank=True)), ("metadata", models.JSONField(blank=True, default=dict)),
            ("board", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="files", to="core.boardmodel")),
            ("component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="files", to="core.componentmodel")),
            ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="files", to="core.project")),
        ], options={"ordering":["-created_at"]}),
        migrations.CreateModel(name="RepositoryLink", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("provider", models.CharField(choices=[("github","GitHub"),("gitlab","GitLab"),("local","Local"),("other","Other")], default="other", max_length=20)),
            ("name", models.CharField(max_length=255)), ("url", models.URLField(blank=True)), ("local_path", models.CharField(blank=True, max_length=500)), ("default_branch", models.CharField(blank=True, max_length=120)), ("metadata", models.JSONField(blank=True, default=dict)),
            ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="repositories", to="core.project")),
        ]),
        migrations.CreateModel(name="Spool", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("spool_id", models.CharField(max_length=40, unique=True)), ("initial_weight_g", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("remaining_weight_g", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ("purchase_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("currency", models.CharField(default="GBP", max_length=3)), ("location", models.CharField(blank=True, max_length=255)),
            ("status", models.CharField(choices=[("sealed","Sealed"),("open","Open"),("drying","Drying"),("empty","Empty"),("retired","Retired")], default="sealed", max_length=20)),
            ("opened_on", models.DateField(blank=True, null=True)), ("last_dried_at", models.DateTimeField(blank=True, null=True)), ("external_spool_id", models.CharField(blank=True, max_length=255)), ("notes", models.TextField(blank=True)),
            ("filament", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="spools", to="core.filamentproduct")),
        ], options={"ordering":["spool_id"]}),
        migrations.CreateModel(name="Model3D", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("name", models.CharField(max_length=255)), ("description", models.TextField(blank=True)), ("source_url", models.URLField(blank=True)), ("license", models.CharField(blank=True, max_length=120)), ("tags", models.JSONField(blank=True, default=list)),
            ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="models_3d", to="core.project")),
        ], options={"ordering":["name"]}),
        migrations.CreateModel(name="ModelRevision", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("version", models.CharField(max_length=80)), ("notes", models.TextField(blank=True)), ("stl_file", models.FileField(blank=True, null=True, upload_to="models/stl/", validators=[core.validators.validate_maker_file])),
            ("three_mf_file", models.FileField(blank=True, null=True, upload_to="models/3mf/", validators=[core.validators.validate_maker_file])), ("cad_file", models.FileField(blank=True, null=True, upload_to="models/cad/", validators=[core.validators.validate_maker_file])),
            ("source_url", models.URLField(blank=True)), ("geometry_metadata", models.JSONField(blank=True, default=dict)), ("slicer_metadata", models.JSONField(blank=True, default=dict)),
            ("model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="core.model3d")),
        ], options={"ordering":["-created_at"]}),
        migrations.AddConstraint(model_name="modelrevision", constraint=models.UniqueConstraint(fields=("model","version"), name="unique_model_revision")),
        migrations.CreateModel(name="ProductListing", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("marketplace", models.CharField(choices=[("amazon","Amazon"),("aliexpress","AliExpress"),("ebay","eBay"),("manufacturer","Manufacturer"),("other","Other")], default="other", max_length=30)),
            ("title", models.CharField(max_length=500)), ("url", models.URLField(max_length=1000)), ("seller", models.CharField(blank=True, max_length=255)), ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ("currency", models.CharField(default="GBP", max_length=3)), ("pack_quantity", models.DecimalField(decimal_places=3, default=1, max_digits=12)), ("image_url", models.URLField(blank=True, max_length=1000)),
            ("external_id", models.CharField(blank=True, max_length=255)), ("source_data", models.JSONField(blank=True, default=dict)),
            ("board", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="listings", to="core.boardmodel")),
            ("component", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="listings", to="core.componentmodel")),
            ("filament", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="listings", to="core.filamentproduct")),
        ], options={"ordering":["-updated_at"]}),
        migrations.CreateModel(name="PrintJob", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)),
            ("status", models.CharField(choices=[("planned","Planned"),("printing","Printing"),("success","Success"),("failed","Failed"),("cancelled","Cancelled")], default="planned", max_length=20)),
            ("quantity", models.PositiveIntegerField(default=1)), ("filament_used_g", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ("waste_g", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ("material_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)), ("currency", models.CharField(default="GBP", max_length=3)), ("estimated_minutes", models.PositiveIntegerField(blank=True, null=True)),
            ("actual_minutes", models.PositiveIntegerField(blank=True, null=True)), ("layer_height_mm", models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)), ("nozzle_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ("slicer", models.CharField(blank=True, max_length=120)), ("settings", models.JSONField(blank=True, default=dict)), ("notes", models.TextField(blank=True)),
            ("model_revision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prints", to="core.modelrevision")),
            ("printer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="print_jobs", to="core.printer")),
            ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="print_jobs", to="core.project")),
            ("spool", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="print_jobs", to="core.spool")),
        ], options={"ordering":["-created_at"]}),
    ]
