# Generated by Django for MakerVault project priority/deadline support.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_printjob_printer_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "P1 — Highest"),
                    (2, "P2 — High"),
                    (3, "P3 — Medium"),
                    (4, "P4 — Low"),
                    (5, "P5 — Lowest"),
                ],
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__isnull", True), models.Q(("priority__gte", 1), ("priority__lte", 5)), _connector="OR"),
                name="project_priority_between_1_and_5",
            ),
        ),
    ]
